### ISSUE TITLE
check about the latest release tag

### ISSUE THREAD

**Issue by chenrui333** [Macchina-CLI/macchina#100]
Should the latest release be `0.8.2` rather than `0.8.21`?

**Comment by grtcdr** [comment]
I made a mistake while versioning the latest release, I published version 0.8.2 on crates.io but did not publish it on GitHub, so I published 0.8.21 on both.

This could've been avoided had I followed the proper versioning scheme as suggested by the Rust documentation.

**Comment by chenrui333** [comment]
So sounds like I can go with `0.8.21`? Gonna create a PR now.

**Comment by chenrui333** [comment]
Created a [upgrade PR](https://github.com/Homebrew/homebrew-core/pull/78009)

**Comment by grtcdr** [comment]
> So sounds like I can go with `0.8.21`?

Yup!

> Created a upgrade PR

Great, sorry about the confusion

**Comment by chenrui333** [comment]
no worries, just want to double check. things can happen! 😄
