### ISSUE TITLE
[Idea] Get GPU info

### ISSUE THREAD

**Issue by PandaFoss** [Macchina-CLI/macchina#107]
### First question, where to get the information from?

I found in the [pciutils repository](https://github.com/pciutils/pciutils) the following:

> In runs on the following systems:
> 
>	Linux		(via /sys/bus/pci, /proc/bus/pci or i386 ports)
>	FreeBSD		(via /dev/pci)
>	NetBSD		(via libpci)
>	OpenBSD		(via /dev/pci)
>	GNU/kFreeBSD	(via /dev/pci)
>	Solaris/i386	(direct port access)
>	Aix		(via /dev/pci and odmget)
>	GNU Hurd	(direct port access)
>	Windows		(direct port access, see README.Windows for caveats)
>	CYGWIN		(direct port access)
>	BeOS		(via syscalls)
>	Haiku		(via /dev/misc/poke)
>	Darwin		(via IOKit)
>	DOS/DJGPP	(via i386 ports)
>	SylixOS		(via /proc/pci)

There are many possible places to search, depending on the kernel (or operating system). But in some cases it's a matter of reading a plain text file. In order not to make the issue too long, I recommend the first part of [this article](https://prefetch.net/articles/linuxpci.html). As you can see in the article, it is possible to read the _vendor_ identifier, _device_ identifier and class identifier.

### Step two: mapping identifiers to GPUs 

I quote again the previous repository, the following:

> The database of PCI IDs (the pci.ids file) gets out of date much faster
> than I release new versions of this package, so it is maintained separately.
> 
> It lives at https://pci-ids.ucw.cz/, where you can browse the database,
> download the most recent pci.ids file (e.g., by running the update-ids utility)
> and also submit new entries.

If we go through that website, we can corroborate that the GPU information (in addition to other devices that are not relevant) can be **obtained from these ID's**.

At first I thought that the `pci.ids` file should be downloaded regularly to keep it updated but, at least in Arch Linux, I found it in `/usr/share/hwdata/pci.ids`.

I'm not sure this is the best way to solve it, but I think it can work, without relying on system commands or external crates.

**Comment by grtcdr** [comment]
I'm afraid the future won't be shipped until I can sort out the performance issues within aparato.

**Comment by grtcdr** [comment]
*sneak peek*

[Uploading image.png…]()

**Comment by PowerBall253** [comment]
What's the current status on this? I'd love to help, as I have some Rust experience.

**Comment by grtcdr** [comment]
Hi @PowerBall253,

Thanks for taking interest!

aparato was originally supposed to help us determine this information, but it's been unmaintained for a very long now. If you'd like to contribute, I suggest looking at other pci.ids parsers and hooking them with libmacchina, then we can add support for that readout in macchina.

**Comment by Rolv-Apneseth** [comment]
Hi, I have no experience with this but I would like to work on as I would like to have that output. I would appreciate some guidance if you can point me in the right direction. 

So, first I find a library which can parse `psi.ids`, maybe like (this one)[https://crates.io/crates/pci-ids]? Do I then use some other method to get the currently connected pci vga device or how do I go about this?

**Comment by Rolv-Apneseth** [comment]
Ok thanks for the guidance, I'll have a look at it when I have some free time for sure and come back here if I get stuck

**Comment by Rolv-Apneseth** [comment]
I have something working. Does this issue need to be moved to [libmacchina](https://github.com/Macchina-CLI/libmacchina) first or shall I just open a PR over there? I also have some code ready for `macchina` to actually display the GPU.

**Comment by Rolv-Apneseth** [comment]
Since that pr has been merged to `libmacchina`, is there a version update that needs to happen before I can make a pr here to utilise the new functionality? I have code ready just not sure if the crate needs an update first.

**Comment by Rolv-Apneseth** [comment]
Ok cool, thank you

**Comment by luccahuguet** [comment]
this issue was created in may 2021, and I just needed this today, exactly when it is very close to being merged... feeling lucky!

thank you very much for the project Macchina team, and the gpu part too @Rolv-Apneseth

**Comment by JacobTravers** [comment]
The newest commit related to this issue seems to be broken for me
```
thread 'main' panicked at 'Could not find opening square bracket for sub device: Reference RX 5700 XT', /home/user/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/libmacchina-6.4.0/src/linux/pci_devices.rs:86:22
```

**Comment by Rolv-Apneseth** [comment]
It was working before and only the latest commit broke it? That's weird, but I'll have a look as it's just a matter of how the strings are being processed I think

**Comment by Rolv-Apneseth** [comment]
> He's using device `731f 1002 0b36` which doesn't have a subdevice name. We should return the device string when an opening brace can't be located.

Alright will do

**Comment by uttarayan21** [comment]
Is it not implemented for windows ?
![image](https://user-images.githubusercontent.com/18732700/228163599-2671ebe7-e4f4-4fac-a0c6-0be44189e4b6.png)

**Comment by Rolv-Apneseth** [comment]
No sorry not yet, I only implemented it for Linux. I believe it would also require internet access to get `pci.ids`.

**Comment by JacobTravers** [comment]
> @JacobTravers Can you `git pull` and try again?

Works fine now 👍🏽

**Comment by Rolv-Apneseth** [comment]
Thanks for reporting that issue @JacobTravers
