### ISSUE TITLE
Use winfetch for comparison

### ISSUE THREAD

**Issue by rashil2000** [Macchina-CLI/macchina#108]
Comparison on Windows shouldn't be done with neofetch. Neofetch on Windows runs with MSys2/Cygwin, which use a POSIX emulation layer. Since it is emulating bash, it will always be slower, no matter what. Bash is not a native shell in Windows. 

For a fairer comparison, please use [winfetch](https://github.com/kiedtl/winfetch). Macchina is still faster, but only by 2x (compared to 250x with neofetch 😅)

**Comment by grtcdr** [comment]
Hey @rashil2000 :)

> Since it is emulating bash, it will always be slower, no matter what. Bash is not a native shell in Windows.

We know, but I think in this stage, the best way to go about it is that we should no longer compare _macchina_ against any other fetcher. Instead, we should provide only the benchmarks of macchina.

By the way, winfetch looks really cool!

**Comment by rashil2000** [comment]
> Instead, we should provide only the benchmarks of macchina.

That would indeed be better!

Currently the Readme mentions neofetch heavily, so for Windows it's slightly misleading since neofetch is a bash script. Until all mentions of neofetch are removed (as you said), I think it'd be better to include a sidenote there (or just do the comparison with winfetch itself, I have hyperfine installed and I can run benchmarks for you), at least for the time being.

**Comment by grtcdr** [comment]
> I think it'd be better to include a sidenote there (or just do the comparison with winfetch itself, I have hyperfine installed and I can run benchmarks for you), at least for the time being.

As I mentioned, we'll refrain from benchmarking macchina against anything in the future, after all, the point of macchina is not to compete with any fetcher. It'd be dumb if we did considering how many features other fetchers have over macchina.

**Comment by rashil2000** [comment]
Great, thanks for the prompt action!

(just a note, I think you forgot to remove the `Relative` column)

**Comment by grtcdr** [comment]
I did, thanks a ton for pointing that out!
