### ISSUE TITLE
Text To Speech Support

### ISSUE THREAD

**Issue by grtcdr** [Macchina-CLI/macchina#109]
[This post](https://lemmy.ml/post/71814) has made me aware of the difficulties blind people can come across when using programs.

This will of course be a feature one can enable on their own. It's time fetchers started targeting a wider audience. :smile: 

If any of you lovely people has any expertise in accessibility features and can help implement this one or can help provide us with ideas, we'd really appreciate it! :heart:

**Comment by uttarayan21** [comment]
Well I have a library or more specifically rust bindings to a python library. https://github.com/uttarayan21/google_speech_rs that makes it super easy to do tts. But I haven't tested it super extensively.

**Comment by grtcdr** [comment]
> Also you swapped the () [] around in the link lol

:laughing:

> Well I have a library or more specifically rust bindings to a python library. https://github.com/uttarayan21/google_speech_rs that makes it super easy to do tts. But I haven't tested it super extensively.

I'll be allocating a little bit of time to try and get this to work, and see if we can have this feature out with the next release.

**Comment by grtcdr** [comment]
Is it on crates.io?

**Comment by uttarayan21** [comment]
No I didn't really publish it since I since I didn't test it extensively.

**Comment by grtcdr** [comment]
I'll just clone and test it locally then, thanks for sharing! :rocket:

**Comment by uttarayan21** [comment]
Sure no problem ! Good luck !

**Comment by grtcdr** [comment]
Any dependencies I should be installing? I'm getting a ton of build errors?

**Comment by grtcdr** [comment]
Google's guide mentions that one should install  `sox` and `libsox-fmt-mp3`, installing `sox` by itself results in:

```
sox FAIL formats: no handler for given file type `mp3'
PyErr { type: <class 'RuntimeError'>, value: RuntimeError(), traceback: Some(<traceback object at 0x7f00cbe21440>) }
```

libsox-fmt-mp3 is not available in the official Arch repos or the AUR.

A quick `sudo find / -name "*sox*"` finds:
`
...
/usr/lib/sox/libsox_fmt_mp3.so
...
`

So Arch does package the libraries required by google's speech python program, but unfortunately it doesn't work.

**Comment by uttarayan21** [comment]
Optional Deps   : libao: for ao plugin
                  libmad: for mp3 plugin [installed]
                  libid3tag: for mp3 plugin [installed]
                  wavpack: for wavpack plugin
                  libpulse: for pulse plugin [installed]
                  opusfile: for opus plugin
                  twolame: for mp3 plugin [installed]

They are listed as optional dependencies

**Comment by grtcdr** [comment]
I missed these, sorry!

**Comment by grtcdr** [comment]
Your bindings work! :rocket: :smiley:

**Comment by uttarayan21** [comment]
Maybe I should update the dependencies and properly add directions

**Comment by grtcdr** [comment]
I'm all for you publishing this on crates.io, it works + it's great!

**Comment by uttarayan21** [comment]
Then I guess I'll publish it in crates.io

**Comment by grtcdr** [comment]
Awesome! I'll starting using that right away then :)

**Comment by grtcdr** [comment]
Okay, so I managed to make it work, but I feel like it's a very hacky method...

**Comment by grtcdr** [comment]
It takes into account the configuration of course, but ignores bars as I don't see a way we can make google_speech speak "bars" lol.

**Comment by grtcdr** [comment]
#110

**Comment by uttarayan21** [comment]
>  Filled circle, filled circle, filled circle, filled circle, filled circle...

Haha I never knew lol ! That is hilarious.

> For example, instead of reading each digit individually in "5.10.46-1-lts" it should read it like any normal human being lol.

I think that is due to it thinking that the point's are decimal places, however no one has any control over it since the text is send to google servers ant that is what they reply with.


Also about espeak and other similar offline tts engines don't sound quite as natural so that is the reason I made this.

**Comment by grtcdr** [comment]
> I think that is due to it thinking that the point's are decimal places, however no one has any control over it since the text is send to google servers ant that is what they reply with.

Ah okay!

> Also about espeak and other similar offline tts engines don't sound quite as natural so that is the reason I made this.

I don't know too much about other TTS engines, and although some won't agree with the fact that we're using Google, if it's the most natural sounding engine, then I'm fine with having it in.

**Comment by uttarayan21** [comment]
> Plus, I think GoogleSpeech works offline? I tested it offline and it still reports data without an internet connection.

If it has same data as a previous call then it is cached. If you try with text that hasn't been said before it will fail if offline.

**Comment by grtcdr** [comment]
I thought about that, thanks for confirming it.

**Comment by grtcdr** [comment]
Closing this as #110 was merged a while ago.
