### ISSUE TITLE
Home directory (~) is not understood in the config file

### ISSUE THREAD

**Issue by rambip** [Macchina-CLI/macchina#113]
I'm pretty sure it is not specific to my machine (arch linux).

I added this line in my `.config/macchina/macchina.toml` config:

```
custom_ascii = "~/.config/macchina/arco-theme"
```

But I get an error:
> Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }

And this file exists: when I use the absolute path

```
custom_ascii = "/home/rambi/macchina/arco-theme"
```
This works.

If this is not a bug, this is clearly a usefull feature that is missing !

**Comment by grtcdr** [comment]
Well it's not necessarily a fault in macchina, but the way paths are handled by TOML.

**Comment by rambip** [comment]
This would be great:
This is meant to be a config file, not a build file :wink:

**Comment by grtcdr** [comment]
> This is meant to be a config file, not a build file

I'm not sure what you mean?

**Comment by grtcdr** [comment]
You've already made your point clear in a previous comment and I said we'd try and expand `~` to `/home/$USER`.

**Comment by rambip** [comment]
Right then
Thanks !
