### ISSUE TITLE
But do you support custom image?

### ISSUE THREAD

**Issue by nyngwang** [Macchina-CLI/macchina#119]
**Describe the bug**

**To Reproduce**
1. But do you support custom image?
2. But do you support custom image?
3. I'm using Alacritty and Neofetch == nnononofetch, so do you support custom image?

![image](https://user-images.githubusercontent.com/24765272/128287372-fad3aaa4-fc91-454f-97cb-7eb272d72355.png)

**Comment by grtcdr** [comment]
Sorry to disappoint, but support for images will most likely never land.
