### ISSUE TITLE
[BUG] macchina outputs `--long-shell` is enabled by default in android.

### ISSUE THREAD

**Issue by uttarayan21** [Macchina-CLI/macchina#125]
**Describe the bug**
In linux macchina outputs only the shell name, whereas in android it outputs the full path of the shell executable.

**To Reproduce**
1. macchina

**Expected behavior**
Output only the shell name

**Screenshots**
![macchina](https://user-images.githubusercontent.com/18732700/129376130-b6ce4f1d-a7c2-4930-947e-0aa2aa5b04ab.jpeg)

**`macchina --doctor` output**
Add a screenshot or copy and paste the output of `--doctor` if an element you're supposed to be seeing isn't showing up.

**System Information**
You don't have to provide this information if you're not comfortable doing so, but it'll help us solve the issue a lot faster.
 - Distribution: Android
 - Desktop Environment [e.g. Plasma]
 - Operating System: Android
 - Terminal: Termux
 - Macchina's version: 0.9.3

**Comment by grtcdr** [comment]
Hey, glad you're back!

I'll take a look at this and report back.

**Comment by uttarayan21** [comment]
Haha, finally fixed the desktop and can do some work again.

**Comment by grtcdr** [comment]
```
        if let Some(shell) = std::env::var_os("SHELL") {
            Ok(shell.to_string_lossy().to_string())
```

This right here is the culprit.

**Comment by grtcdr** [comment]
We could pass it to `extra::basename()` and it should give us back the shell name.

**Comment by uttarayan21** [comment]
Yeah that sounds good !

**Comment by grtcdr** [comment]
For some reason, I might've removed the basename function though.

**Comment by grtcdr** [comment]
[fsio](https://crates.io/crates/fsio) has it.

**Comment by uttarayan21** [comment]
https://boinkor.net/2019/07/basename-and-dirname-in-rust/
Seems like the standard library might have a basename called Path::file_name

**Comment by grtcdr** [comment]
We can go with that then :)

**Comment by grtcdr** [comment]
https://github.com/Macchina-CLI/libmacchina/commit/8f47048f5a40d6e39b0d7fcba020f1d4a2def439 should fix this, and I should also set up some mock tests.

**Comment by grtcdr** [comment]
It should work as expected with libmacchina's latest version.

**Comment by uttarayan21** [comment]
Now it displays short shell but the `--long-shell` flag doesn't work anymore.

**Comment by grtcdr** [comment]
Great! I'll close this then.
