### ISSUE TITLE
[BUG] unable to read default macchina.toml

### ISSUE THREAD

**Issue by rbrtbrnschn** [Macchina-CLI/macchina#128]
**Describe the bug**
Macchina is unable to read the "default" config file `macchina.toml` as provided in the readme.  

**To Reproduce**
1. download or copy macchina.toml from the readme and put in `$XDG_CONFIG_HOME/macchina/`
2. run `macchina`
3. voila => warning appears: *Warning: Failed to parse config*

**Expected behavior**
It should atleast be able to read it :D

**Screenshots**
![image](https://user-images.githubusercontent.com/56562982/129455015-025b5bd7-0b23-496f-a871-4fef5f1e19fa.png)
![image](https://user-images.githubusercontent.com/56562982/129455079-a76d338a-e275-41d6-a0e6-86f167591749.png)

**`macchina --doctor` output**
Add a screenshot or copy and paste the output of `--doctor` if an element you're supposed to be seeing isn't showing up.

**System Information**
![image](https://user-images.githubusercontent.com/56562982/129455060-c5c3f2cc-b23a-484a-8f42-9adde00e573c.png)

Config:
https://raw.githubusercontent.com/Macchina-CLI/macchina/main/macchina.toml

**Comment by uttarayan21** [comment]
It's the `current_shell` flag causing trouble. You can comment it for now. In the mean time I'll try to fix the bug.
