### ISSUE TITLE
Any chance of a bugfix release?

### ISSUE THREAD

**Issue by 414owen** [Macchina-CLI/macchina#134]
I'm on 1.0.0 and am affected by https://github.com/Macchina-CLI/macchina/issues/131

It would be great to get a `1.0.1` release (also potentially a 0.9.4, although I'm not personally invested in the 0.9.x branch).

If the version's updated here, I'll be able to run an automated tool to update the version in `nixpkgs` :)

**Comment by grtcdr** [comment]
Sure, I'll have a look at what's causing the issue as soon as I can.

**Comment by 414owen** [comment]
Thanks! I thought it was fixed in https://github.com/Macchina-CLI/macchina/pull/132?

**Comment by grtcdr** [comment]
Me too.

May I ask for a log? (It would help if you build from source) so I can try and inspect the source of the issue?

**Comment by uttarayan21** [comment]
I think @414owen is asking for a new release with the bug fix included since its not included in the latest release.

**Comment by grtcdr** [comment]
Oh, really? My bad. I'll publish a release then :)

**Comment by grtcdr** [comment]
@uttarayan21 your commit feature saved my day :smile:

**Comment by grtcdr** [comment]
@414owen v1.1.1 should have all the latest stuff :)

**Comment by 414owen** [comment]
Thanks @grtcdr

**Comment by grtcdr** [comment]
You're welcome, are the issues gone for good?
