### ISSUE TITLE
[BUG] Won't read config file from $XDG_CONFIG_HOME/macchina/macchina.toml

### ISSUE THREAD

**Issue by EjPlatzer** [Macchina-CLI/macchina#136]
**Describe the bug**
Macchina won't read my config file even though it's in the correct location and can be parsed successfully.
It doesn't seem to be a parsing issue with my config file, because if I manually specify the config file, it works perfectly.

Platform is Macos, installed via nix package manager

**To Reproduce**
1. Install macchina
2. Create macchina.toml file at `$XDG_CONFIG_HOME/macchina/macchina.toml`
3. run `macchina`

**Expected behavior**
It should use my config file by default, since it's in the default location. 

**Screenshots**
![macchina](https://user-images.githubusercontent.com/35319956/131735518-5feeefba-ae15-4939-882f-ec236a7951bb.png)

**System Information**
 - Operating System:  macOS
 - Terminal: Alacritty
 - Macchina's version: 0.9.2

**Comment by EjPlatzer** [comment]
That worked, thank you!

Perhaps the readme should reflect that, since the way it's currently phrased, "In order for Macchina to read your dotfile, you need to place macchina.toml in `$XDG_CONFIG_HOME/macchina`", suggests that Macchina will read config from there automatically.

**Comment by uttarayan21** [comment]
macchina does read it automatically but it works only on linux. There was also issue #94 due to that. Probably should update the readme reflecting that.

**Comment by grtcdr** [comment]
> macchina does read it automatically but it works only on linux. There was also issue #97 due to that. Probably should update the readme reflecting that.

Do you think this is related to XDG's variables?

We should probably do something about this so we don't confuse any more people.

**Comment by grtcdr** [comment]
> That worked, thank you!
> 
> Perhaps the readme should reflect that, since the way it's currently phrased, "In order for Macchina to read your dotfile, you need to place macchina.toml in `$XDG_CONFIG_HOME/macchina`", suggests that Macchina will read config from there automatically.

Yeah sorry about. I was never aware that XDG variables were not a thing on macOS. I'm sure this works just fine on the BSDs though, as we've never had any complaints about this issue on those platforms. I'll find a workaround that doesn't involve user intervention.

**Comment by EjPlatzer** [comment]
I use XDG variables when possible on my Mac, but it is true that most applications default to `~/Library/Application Support/`. Maybe it's possible to check if `$XDG_CONFIG_HOME` is set, or default to a platform-specific one otherwise?

**Comment by grtcdr** [comment]
Yes, I agree that a check should be performed before blindly assuming it exists there.  But I'm not sure whether to go with `~/Library/Application Support/` or `~/Library/Preferences`. What do you think?

**Comment by grtcdr** [comment]
That should work!

I'll dig through `dirs-rs` and see if I can solve this issue upstream, so everybody benefits. I'm not sure if this check is within the scope of the crate, though.

**Comment by EjPlatzer** [comment]
Thank you very much @grtcdr and @uttarayan21 !! The quick, helpful response and immediate action is really above and beyond for open source maintenance. I appreciate this tool and your contributions to it!

**Comment by grtcdr** [comment]
You're very welcome! Thank you for the kind words :heart:

**Comment by grtcdr** [comment]
I've decided to manually create a `PathBuf` that holds the path of the config to properly read from, but it isn't `~/Library/Application Support`. The reason being is some people have said that none of their CLI programs actually place their configs there.

**Comment by grtcdr** [comment]
It'll look for `macchina.toml` in `~/.config/macchina` without the use of `dirs-rs` in a macOS environment.

**Comment by uttarayan21** [comment]
@gennaro-tedesco  Can you post your ```macchina.toml``` so that I can reproduce it. We'll try to make the changes non-breaking from now on.

**Comment by gennaro-tedesco** [comment]
My current `macchina.toml` is the below:
```
no_separator = true

no_bar_delimiter = true

no_title = true

no_ascii = true

palette = false

bar = false

color = "Cyan"

short_uptime = true

long_shell = true

box_inner_margin_x = 3

box_inner_margin_y = 1

show_only = [
	"Host",
	"Machine",
	"Kernel",
	"OperatingSystem",
	"Terminal",
	"Shell",
	"ProcessorUsage",
	"Memory",
]
```
Moreover
```
$ macchina --version
macchina    1.0.0
libmacchina 0.8.1
```
my OS being `macOS 11.5.2 Big Sur`.

**Comment by grtcdr** [comment]
I'd be a really happy man if you guys helped us test out #137 :)
