### ISSUE TITLE
I can't install macchina v1.1.6-1 on Manjaro GNOME 40.2 [BUG]

### ISSUE THREAD

**Issue by IngrownMink4** [Macchina-CLI/macchina#147]
**Describe the bug**
I can't install macchina on Manjaro. It says: "¡One or more files did not pass validation check!"
Before upgrading to v1.x.x branch, this error did not happen...

**To Reproduce**
1. Open Pamac
2. Search for macchina 
3. Compile it
4. When it's "validating source files with sha256sums", then it says that it "HAS FAILED"

**Expected behavior**
A fast and smooth installation of this wonderful software.

**Screenshots**
![macchina](https://user-images.githubusercontent.com/25466522/134070718-128507d0-7247-42db-93fb-906ea1840b62.png)
![macchina2](https://user-images.githubusercontent.com/25466522/134071367-6545b891-6ed2-49f4-b511-1d36fd0487da.png)
![Captura de pantalla de 2021-09-20 22-31-59](https://user-images.githubusercontent.com/25466522/134071423-8da50986-ee59-499f-9107-4d4b2b73fd11.png)

**System Information**
You don't have to provide this information if you're not comfortable doing so, but it'll help us solve the issue a lot faster.
 - Distribution: Manjaro 21.1.3 Pahvo
 - Desktop Environment: GNOME 40.4.0
 - Operating System: GNU/Linux
 - Terminal: GNOME Terminal
 - Macchina's version: v1.1.6-1

**Comment by grtcdr** [comment]
I forgot to update the SHASUM for the new PKGBUILD, give me a few minutes and it'll be fixed :)

**Comment by IngrownMink4** [comment]
Wow, that was fast, thank you very much!
![thanks](https://user-images.githubusercontent.com/25466522/134389689-3d136cc2-4033-4c2e-b939-bb7c71c17717.png)
