### ISSUE TITLE
Arch linux ascii art not displayed

### ISSUE THREAD

**Issue by reportaman** [Macchina-CLI/macchina#152]
On arch linux the ascii art is not displayed, instead a linux ascii art is. I see there is a file in the repository under https://github.com/Macchina-CLI/macchina/blob/main/ascii/archlinux.ascii, is there a plan to support distro logos as ascii art like neofetch does?

**Comment by grtcdr** [comment]
There's currently no plan to support automatic picking of distribution ASCII art.

But we do provide you with the option to use whatever ASCII art you'd like through the `custom_ascii` flag. It accepts text files and supports ANSI color coding.
