### ISSUE TITLE
[BUG] Wrong/Incomplete Information

### ISSUE THREAD

**Issue by VarLad** [Macchina-CLI/macchina#184]
The shell I'm using is nushell
Doesn't display brightness, resolution, CPU Load and Battery
For version 5.0.0

Here's the information from doctor
```
[varlad@fedora Downloads]$ ./macchina -d
Let's check your system for errors... Here's a summary:

We've collected 18 readouts, including 1 failed read(s) and 1 read(s) which resulted in a warning.
Readout "LocalIP" failed with message: Please specify a network interface to query (e.g. `interface = "wlan0"` in macchina.toml).

1 of the 2 unsuccessful read(s) resulted in a warning:
Readout "OperatingSystem" threw a warning with message: This metric is not available on this platform or is not yet implemented by Macchina.
```

**Comment by VarLad** [comment]
![Screenshot from 2021-11-01 17-19-35](https://user-images.githubusercontent.com/51269425/139667449-5be88b3d-04b7-4395-bed8-94ea37c72877.png)

**Comment by VarLad** [comment]
The execution method was to download the binary from releases
Then `chmod +x machhina-linux-x86_64`
followed by `./machhina-linux-x86_64`

**Comment by VarLad** [comment]
Installing version 4.0.1 somewhat works
![Screenshot from 2021-11-01 17-41-41](https://user-images.githubusercontent.com/51269425/139669495-cc3092cb-028c-4c0e-a404-b913543c6413.png)
Now to figure how do I display percentage instead of dots....

**Comment by grtcdr** [comment]
I can't really help you with v4.0.1, can you jump back to v5.0.0 and paste your theme and configuration file?

**Comment by VarLad** [comment]
@grtcdr I didn't define a theme or configuration file
The above output is for whatever is default/out of the box

**Comment by VarLad** [comment]
@grtcdr After defining configuration file
```
# Specifies the network interface to use for the LocalIP readout
interface = "wlan0"

# Lengthen uptime output
long_uptime = true

# Lengthen shell output
long_shell = false

# Lengthen shell output
long_kernel = false

# Toggle between displaying the current shell or your user's default one.
current_shell = true

show = ["Battery", "Memory", "OperatingSystem", "Machine", "Kernel", "Distribution", "Resolution", "Processor"]
```
![Screenshot from 2021-11-01 18-40-16](https://user-images.githubusercontent.com/51269425/139676770-b7b9d406-0d6c-4be0-bd65-05c29d31e770.png)

**Comment by grtcdr** [comment]
That is true, the default theme has a problem with the bar glyphs. I'll get that fixed ASAP.

Any other issues?

**Comment by VarLad** [comment]
Any way I get percentage instead of bars?
Or

**Comment by grtcdr** [comment]
We don't have such a feature at the moment.

> Also, regarding shell, why does it show bash instead of nushell?

shell output depends on `current_shell`, what's your default shell and which one are you currently using in your terminal emulator?

**Comment by VarLad** [comment]
> shell output depends on current_shell, what's your default shell and which one are you currently using in your terminal emulator?

Okay, now it shows nu after I launch it with `--current-shell`

**Comment by grtcdr** [comment]
Your configuration already sets that (`current_shell = true`)

**Comment by VarLad** [comment]
Okay thanks
Regarding information, how can I get text instead of bars?
Something like this https://user-images.githubusercontent.com/35816711/128879461-dfa06c0e-2775-4379-8dd8-8c9e377367cd.png

**Comment by grtcdr** [comment]
Can you tell me the output of `grep "^$USER" /etc/passwd`?

**PLEASE HIDE ANY PERSONAL INFORMATION**

**Comment by grtcdr** [comment]
> Okay thanks Regarding information, how can I get text instead of bars? Something like this https://user-images.githubusercontent.com/35816711/128879461-dfa06c0e-2775-4379-8dd8-8c9e377367cd.png

You'll want to create a theme with bars being visible. Have a look at the [themes section](https://github.com/Macchina-CLI/macchina#features)

**Comment by VarLad** [comment]
> Can you tell me the output of grep `"^$USER" /etc/passwd?`

I think you're asking me that for the default shell
It says `/bin/bash` if thats what you want :smiley:

**Comment by grtcdr** [comment]
Okay, great. If you'd like to see your current shell, be sure to set that to true and you should be alright.

**Comment by grtcdr** [comment]
I've fixed the issue with the bars https://github.com/Macchina-CLI/macchina/commit/c5beaf95e0892f36ba6a79f2e6858a5d5791d70a.

**Comment by VarLad** [comment]
Is this good enough for a minor re-release?

**Comment by grtcdr** [comment]
Yes :)

**Comment by VarLad** [comment]
Great!
Thanks for helping with the issue :smile: 
Also, the speed of this thing is outright black magic! :laughing:

**Comment by grtcdr** [comment]
> Thanks for helping with the issue

You're very welcome :)

> Also, the speed of this thing is outright black magic!

I know, it's pretty cool :rocket:

**Comment by VarLad** [comment]
Ah right, another question
I think `macchina` still doesn't have session (X and Wayland)
That'd be convenient
Should I open a feature request for it? :sweat_smile:

**Comment by grtcdr** [comment]
Sure, go ahead.

**Comment by VarLad** [comment]
Closing this issue, thanks again!
