### ISSUE TITLE
[IDEA]  Support for showing sessions (X11 or Wayland)

### ISSUE THREAD

**Issue by VarLad** [Macchina-CLI/macchina#185]
macchina doesn't have `session` (to display X or Wayland in Linux) 
That'd be convenient

**Comment by grtcdr** [comment]
Is it okay if we append this to the output of your Window Manager?

For example:

```
WM  ->  Sway (Wayland)
or
WM  ->  Mutter (X11)
```

**Comment by VarLad** [comment]
Yeah, that'd be even better

**Comment by grtcdr** [comment]
It's in https://github.com/Macchina-CLI/macchina/commit/60128e00bf57c98f33adcb5a292d56f4151cb833 :partying_face:

**Comment by VarLad** [comment]
I'll be honest, once it can show GPU info, macchina should be the best de-facto fetch program :laughing:

**Comment by grtcdr** [comment]
(aparato)[https://github.com/grtcdr/aparato] was actually created solely to bring GPU information to libmacchina (and macchina), without any sort of weird dependencies. Unfortunately, it proved to be really hard to maintain multiple projects at once.

I plan to get back to aparato some day to optimize it and fix its inherent issues, like the slowness and inaccuracy. But I don't know when that will happen, university is just too time consuming.

**Comment by VarLad** [comment]
> university is just too time consuming.

True, that. :smiley: 
I hope it happens soon!

**Comment by grtcdr** [comment]
Just a heads up on the session readout: if macchina fails to fetch your window manager (or if you don't have `wmctrl` installed), then session information will not show up as well.
