### ISSUE TITLE
[BUG] couldn't report shell correctly 

### ISSUE THREAD

**Issue by dcai** [Macchina-CLI/macchina#192]
**Describe the bug**
I'm running fish shell, but reported as zsh, please see screenshot:
<img width="676" alt="image" src="https://user-images.githubusercontent.com/7065/140257820-00fae1de-8043-4b56-a78a-952668b410fb.png">

**To Reproduce**
1. Launch terminal
2. enter `macchina`
3.

**Expected behavior**
should show fish shell

**Screenshots**

<img width="329" alt="image" src="https://user-images.githubusercontent.com/7065/140258104-7b6277b7-b5d8-4c46-b1d1-dfce05f88b36.png">

<img width="676" alt="image" src="https://user-images.githubusercontent.com/7065/140257857-daa3a23e-cd2b-458c-8272-2e28f6a6c313.png">

**`macchina --doctor` output**
```Let's check your system for errors... Here's a summary:

We've collected 18 readouts, including 1 failed read(s) and 2 read(s) which resulted in a warning.
Readout "LocalIP" failed with message: Please specify a network interface to query (e.g. `interface = "wlan0"` in macchina.toml).

2 of the 3 unsuccessful read(s) resulted in a warning:
Readout "Distribution" threw a warning with message: Since you're on macOS, there is no distribution to be read from the system.
Readout "Backlight" threw a warning with message: This metric is not available on this platform or is not yet implemented by Macchina.
```

**System Information**
You don't have to provide this information if you're not comfortable doing so, but it'll help us solve the issue a lot faster.
 - Distribution: macOS 12.0.1
 - Desktop Environment [e.g. Plasma]
 - Operating System macOS
 - Terminal iTerm2
 - Macchina's version 4.0.1

**Comment by 123marvin123** [comment]
Sadly, we haven't found a way to read the actual currently used shell when running macchina. The `$SHELL` variable is not present, so we have to use the default shell for the user. On macOS, you can check your default shell using 

```bash
dscl . -read ~/ UserShell
```

Mine displays `UserShell: /opt/homebrew/bin/fish` and when running macchina, I get that readout too. As long as we don't have a way of getting the actual shell, reading the default shell is our best guess.

**Comment by dcai** [comment]
@123marvin123 thanks for the prompt explanation, closing the report as no visible solution for now.
