### ISSUE TITLE
[INFO] openSUSE distro packaging

### ISSUE THREAD

**Issue by Stig124** [Macchina-CLI/macchina#196]
Hello,
This post is to inform that I proposed (and will maintain it going forward) my `.rpm` build of `macchina` to the official openSUSE repos for Tumbleweed, the package is already downloadable on the `utilities` repository of the the openSUSE's [openbuildservice instance](https://software.opensuse.org//download.html?project=utilities&package=macchina)

Contribution to the spec is possible (see the spec [here](https://build.opensuse.org/package/show/utilities/macchina])) and encouraged

I'd like to add that to the install wiki, but edit is blocked

**Comment by grtcdr** [comment]
Thank you so much for helping out :smile: 

If the installation is a one-liner or (a few lines), then you can create a PR to include it in the README and I'll gladly accept it. If not, I can open the wiki for editing.

**Comment by Stig124** [comment]
> Thank you so much for helping out smile
> 
> If the installation is a one-liner or (a few lines), then you can create a PR to include it in the README and I'll gladly accept it. If not, I can open the wiki for editing.

No problem, it's great to help

It is one lined (`zypper in macchina`), but not exactly applicable right now (waiting for request of addition to be fullfilled), will make a WIP PR and mark it at ready when the request is fullfilled

**Comment by grtcdr** [comment]
Alrighty, *excited noises* :)

**Comment by Stig124** [comment]
PR done
