### ISSUE TITLE
[BUG] DE info for KDE Plasma

### ISSUE THREAD

**Issue by VarLad** [Macchina-CLI/macchina#199]
DE info for KDE Plasma doesn't display properly

![Screenshot from 2021-11-06 05-10-55](https://user-images.githubusercontent.com/51269425/140589687-860aa621-dc53-4c6b-afb3-b74f6b5c8f54.png)

Any way we could get a better looking message?
(I get that the `Distro` displays it)

**Comment by grtcdr** [comment]
There are unfortunately no elegant ways to solve this, this is more of a Plasma issue.

You can confirm this by echoing `XDG_CURRENT_DESKTOP` in your shell. Also, the path you see doesn't exist unless you append some extension. GNOME and other DEs don't have this issue, they (mostly) report a clean output.

I can add an exception, but I really don't see why we should, especially when there's no compelling reason for Plasma to display a path as its `XDG_CURRENT_DESKTOP`.

> (I get that the `Distro` displays it)

Your distribution should probably not display that kind of information, as it's not exactly relevant (at least in the `/etc/os-release` file which we get the distribution information from.)

**Comment by Allevry** [comment]
for me, XDG_CURRENT_DESKTOP gave the desired output
![Screenshot_20211106_111704](https://user-images.githubusercontent.com/68745123/140599467-d32b470f-cf0e-4180-a7e3-5fbbf3a30967.png)

**Comment by VarLad** [comment]
Also, @grtcdr 
The `/etc/os-release` file doesn't mention the keyword KDE at all
```
NAME="Fedora Linux"
VERSION="35 (Workstation Edition)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Workstation Edition)"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**Comment by FantasyTeddy** [comment]
The DE is determined by *libmacchina* by looking at `DESKTOP_SESSION` **and** `XDG_CURRENT_DESKTOP` (in this order).

@Allevry: Could you confirm that `DESKTOP_SESSION` contains the path displayed in *macchina* instead of a simple name?

@grtcdr: Maybe we could switch the order of those two environment variables and give `XDG_CURRENT_DESKTOP` precedence?

**Comment by Allevry** [comment]
@FantasyTeddy yes it showed the path ! I guess we can change the order for libmacchina

**Comment by grtcdr** [comment]
> @FantasyTeddy yes it showed the path ! I guess we can change the order for libmacchina

I don't think we can do that without side-effects on other DEs.

**Comment by FantasyTeddy** [comment]
What kind of side-effects are you worried about?
This post on [superuser.com](https://superuser.com/a/1643180) points out that `XDG_CURRENT_DESKTOP` is the official standard and `DESKTOP_SESSION` is deprecated and only set as backward-compatibility (which *macchina* should not rely on in my opinion).

**Comment by grtcdr** [comment]
Well, in that case, I'll swap the order.

**Comment by grtcdr** [comment]
Done, https://github.com/Macchina-CLI/libmacchina/commit/52e614ac3010192846c70dfa5e5ab607508dfbb1.

**Comment by grtcdr** [comment]
This will appear in [v|](#200)
