### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by di-effe** [Macchina-CLI/macchina#220]
Hi, love this tool :)
Did someone already shared some themes?
It's kinda hard to google for them with this name :D

**Comment by grtcdr** [comment]
We haven't received any user-uploaded themes, but we are open to include any cool themes created by you (the community) in the repository.

We do have two themes that you can use as a template, see the [themes directory](https://github.com/Macchina-CLI/macchina/tree/main/themes).

The [themes documentation](https://github.com/Macchina-CLI/macchina/wiki/Theme-Documentation) details every available option and what they do.

Does that answer your question?

**Comment by grtcdr** [comment]
I've created a discussion for this very specific issue, see https://github.com/Macchina-CLI/macchina/discussions/222.

**Comment by di-effe** [comment]
Thanks, yes that answer my question :)
Jumping on 222
