### ISSUE TITLE
[BUG] windows version reports invalid theme for provided themes

### ISSUE THREAD

**Issue by bw1faeh0** [Macchina-CLI/macchina#224]
**Describe the bug**
The current windows version of macchina is not able to use the themes provided by this repo

**To Reproduce**
1. download `Hydrogen.toml` and save as `D:\Programme\macchina\themes\Hydrogen.toml`
2. run `macchina-windows-x86_64 -t D:\Programme\macchina\themes\Hydrogen.toml`  

**Expected behavior**
macchina uses the theme

**Screenshots**
![image](https://user-images.githubusercontent.com/29235332/143833512-724b88aa-543e-4481-ade0-bae11e9c9852.png)

![image](https://user-images.githubusercontent.com/29235332/143833566-d5530c89-646f-4764-a435-0b8498274f54.png)

**`macchina --doctor` output**
````
Let's check your system for errors... Here's a summary:

We've collected 18 readouts, including 2 failed read(s) and 8 read(s) which resulted in a warning.
Readout "Packages" failed with message: No packages found — Do you have a package manager installed?
Readout "LocalIP" failed with message: Unable to get local IP address.

8 of the 10 unsuccessful read(s) resulted in a warning:
Readout "Distribution" threw a warning with message: This metric is not available on this platform or is not yet implemented by Macchina.
Readout "DesktopEnvironment" threw a warning with message: This metric is not available on this platform or is not yet implemented by Macchina.
Readout "WindowManager" threw a warning with message: This metric is not available on this platform or is not yet implemented by Macchina.
Readout "Terminal" threw a warning with message: This metric is not available on this platform or is not yet implemented by Macchina.
Readout "Shell" threw a warning with message: This metric is not available on this platform or is not yet implemented by Macchina.
Readout "Resolution" threw a warning with message: This metric is not available on this platform or is not yet implemented by Macchina.
Readout "Backlight" threw a warning with message: This metric is not available on this platform or is not yet implemented by Macchina.
Readout "ProcessorLoad" threw a warning with message: This metric is not available on this platform or is not yet implemented by Macchina.
````

**System Information**
macchina 5.0.5

**Comment by grtcdr** [comment]
Hi,

This is an issue of misplaced themes, can you place them in `{FOLDERID_RoamingAppData}/macchina/themes`?

That should be `%AppData%/macchina/themes` if I'm not mistaken.

**Comment by bw1faeh0** [comment]
I'll try this as soon as possible, but if this is the reason, it should be mentioned in the documentary that this dir is hard coded. 

I read the documentary about this but was not able to "translate" FOLDER_ID in a valid windows path. 

I assumed that by using the -t switch I'm able to use any file specified by the path I provide.

**Comment by grtcdr** [comment]
I hate to be the "read the readme" guy, but the README covers exactly how to configure and customize macchina.

**Comment by bw1faeh0** [comment]
Ok, I created `%AppData%/macchina` (which is `AppData\Roaming\macchina`) and put my files in there (themes in subdir `themes`). Now it works.

You should add to your readme, that `{FOLDERID_RoamingAppData}` (which I never read before and what me made fail initially) means `%AppData%`.

Thanks for clarification!

**Comment by grtcdr** [comment]
> You should add to your readme, that {FOLDERID_RoamingAppData} (which I never read before and what me made fail initially) means %AppData%.

Will do.

> Thanks for clarification!

You're welcome, your feedback has been very helpful, so thank you! :rocket:
