### ISSUE TITLE
LeftWM, fetched as DE instead of WM

### ISSUE THREAD

**Issue by 0323pin** [Macchina-CLI/macchina#225]
@grtcdr Hi, hope you're doing fine. Just came across an interesting one :)

Usually I have the DE read-out disabled as I don't use one. Yesterday I started to play arround with `leftwm` and finally got it to build and run from git-HEAD, https://i.postimg.cc/hGksKScV/2021-11-29-231906-1366x768-scrot.png

When `macchina` failed to display the WM read-out, I disabled it and enabled the DE one. Surprise, it actually fetches `leftwm` as DE. Not a big deal, just thought I'd let you know.

**Comment by 0323pin** [comment]
> LeftWM is setting XDG_CURRENT_DESKTOP (and it's not being unset when hopping between other WMs)

Btw, this is probably because it uses the `/tmp` directory and I didn't shutdown or, rebooted while shifting WMs, I simply killed X, edited `.xinitrc` and re-launched X.

Need to sleep now ...

**Comment by grtcdr** [comment]
Yeah, that makes sense now, before I forget, can you post `--doctor` output so I know how to go about fixing this?

**Comment by 0323pin** [comment]
Sure, sorry for the delay.

```
/home/pin()
2021-12-02 11:50 > macchina -d
Let's check your system for errors... Here's a summary:

We've collected 12 readouts, including 1 failed read(s) and 0 read(s) which resulted in a warning.
Readout "WindowManager" failed with message: Window manager not available — perhaps it's not EWMH-compliant.
/home/pin()
2021-12-02 11:50 >

```

**Comment by grtcdr** [comment]
Okay, `wmctrl` failed to detect the WM, so it's either we address this internally, or make a request for EMWH-compliance by LeftWM's dev.

**Comment by 0323pin** [comment]
Agreed. Would you like to raise the issue with `leftwm`?

**Comment by grtcdr** [comment]
Yeah, I'll try and file an issue by the end of the day.

**Comment by grtcdr** [comment]
Good news!

The devs have [answered](https://github.com/leftwm/leftwm/issues/596), it should be addressed by the PR they linked.

**Comment by 0323pin** [comment]
@grtcdr So, I'd guess we just need 587 to be merged 😄 

Yeah, I came across your comment, as I'm also interested in the same commit which fixes a bunch of other things.

**Comment by 0323pin** [comment]
No problem, I think we wrote at the same time 😆

**Comment by grtcdr** [comment]
Yeah I think so, something weird happened lol.

Anyways, I'm going to try out LeftWM in the meantime, seems like the right fit for me. Dang, we even have the same theming philosophy.

**Comment by 0323pin** [comment]
🤣 Indeed.
Now, I guess I need to port `polybar` 😪

**Comment by grtcdr** [comment]
But, I've followed your footsteps and got rid of my panel :(

**Comment by 0323pin** [comment]
> But, I've followed your footsteps and got rid of my panel :(

I was just joking.

**Comment by 0323pin** [comment]
@grtcdr The commit was merged on `leftwm` and I've re-built it.
All good!

```
/home/pin()
2021-12-03 11:39 > macchina
                                                                
  Host         pin@mybox                                        
  Machine      Hewlett-Packard HP EliteBook 820 G1 A3009DD10303
  OS           NetBSD 9.99.92                                   
  WM           LeftWM                                           
  Packages     192 (pkgsrc)                                     
  Terminal     xterm                                            
  Shell        nu                                               
  Uptime       7m                                               
  CPU          Intel® Core™ i5-4210U CPU @ 1.70GHz (4)          
  Memory       463.3 MB/7.5 GB                                  
  Battery      97% & Discharging                                
                                                                
                                                                

/home/pin()
2021-12-03 11:39 > macchina -d
Let's check your system for errors... Here's a summary:

We've collected 12 readouts, including 0 failed read(s) and 1 read(s) which resulted in a warning.
🎉 You are good to go! No failures detected.

1 of the 1 unsuccessful read(s) resulted in a warning:
Readout "DesktopEnvironment" threw a warning with message: You appear to be only running a window manager.
/home/pin()
2021-12-03 11:39 > 
```

**Comment by grtcdr** [comment]
Very awesome! That was very quick :runner:
