### ISSUE TITLE
[BUG] Hydrogen theme fails to deserialize

### ISSUE THREAD

**Issue by 123marvin123** [Macchina-CLI/macchina#239]
**Describe the bug**
TOML deserialization of Hydrogen.toml theme fails.

**To Reproduce**
1. Copy contrib/themes/Hydrogen.toml to your local themes folder
2. Try to use Hydrogen theme.

**Expected behavior**
Macchina output appears in the Hydrogen theme.

**Actual behavior**
Macchina output appears in the default theme, silently failing to apply the Hydrogen theme.

**System Information**
You don't have to provide this information if you're not comfortable doing so, but it'll help us solve the issue a lot faster.

 - Operating System: macOS
 - Terminal: iTerm2
 - Macchina's version: 6.0.1

**Comment by 123marvin123** [comment]
The error message we get from the toml deserializer internally is:
`Could not create theme Hydrogen.toml: ParsingError(Error { inner: ErrorInner { kind: Custom, line: Some(8), col: 18, at: Some(166), message: "invalid type: string \"Light\", expected struct Palette", key: ["palette"] } })`

Which means, that the line `palette         = "Light"` in the Hydrogen.toml file is wrong. Palette should be expanded into its own section like in the other themes.

**Comment by grtcdr** [comment]
I'll push out a fix in v6.0.2

**Comment by grtcdr** [comment]
Hydrogen displays properly with https://github.com/Macchina-CLI/macchina/commit/1e7fff019c0b763768dc79272d5fd23afae742ea
