### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by Henrik-N** [Macchina-CLI/macchina#251]
Hey there, I wanted to let you know about some dead links I came across on your wiki page.

The following links result in a 404.

https://github.com/Macchina-CLI/macchina/wiki/Customization: "Theming documentation" and "macchina.toml"
https://github.com/Macchina-CLI/macchina/wiki/Configuration: "Follow me" and "macchina.toml"

**Comment by grtcdr** [comment]
Hi!

Thanks for notifying me about this, each and every link has been restored to point to the correct URL, now.
