### ISSUE TITLE
WindowManager: does not appear on Slackware 15

### ISSUE THREAD

**Issue by slackernetuk** [Macchina-CLI/macchina#252]
System:    Slackware 15
Kernel:     5.16.9
wmctrl:    1.0.7
rust:        1.58.1

wmctrl -m 
```
Name: i3
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: N/A
```
macchina --doctor

```
Let's check your system for errors... Here's a summary:

We've collected 19 readouts, including 5 failed read(s) and 0 read(s) which resulted in a warning.
Readout "OperatingSystem" failed with message: This metric is not available on this platform or is not yet implemented by libmacchina.
Readout "DesktopEnvironment" failed with message: You appear to be only running a window manager.
Readout "WindowManager" failed with message: Metric is not available on this system.
Readout "Packages" failed with message: No packages found — Do you have a package manager installed?
Readout "Battery" failed with message: Got an unexpected value "not charging" reading battery status
```
What does this mean exactly? It sounds like a dependency issue?
`Readout "WindowManager" failed with message: Metric is not available on this system.`

**Comment by grtcdr** [comment]
X11 or Wayland? What window manager is it supposed to be?

If wmctrl can't detect it, neither will macchina unfortunately :((

**Comment by slackernetuk** [comment]
> X11 or Wayland? What window manager is it supposed to be?
> 
> If wmctrl can't detect it, neither will macchina unfortunately :((

i3 tilling window manager  with X11...btw I have the same issues with fluxbox as well.

The output from wmctrl is.
```
Name: i3
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: N/A
```

**Comment by grtcdr** [comment]
What's the output of `echo $XDG_SESSION_TYPE`?

I doubt it's anything other than `x11` or `wayland`, but it wouldn't hurt to check.

**Comment by slackernetuk** [comment]
> What's the output of `echo $XDG_SESSION_TYPE`?
> 
> I doubt it's anything other than `x11` or `wayland`, but it wouldn't hurt to check.

It is working now....the output was tty. Thank you for pointing that out.

**Comment by grtcdr** [comment]
You're welcome! I believe all window managers set `XDG_SESSION_TYPE` to the appropriate display server as soon as they are launched, are you aware of what may have caused the issue?

**Comment by Fxzzi** [comment]
> You're welcome! I believe all window managers set `XDG_SESSION_TYPE` to the appropriate display server as soon as they are launched, are you aware of what may have caused the issue?

Sorry to necropost but I think this is caused when you use xinit or startx for launching your WM. Same problem happened to me.
