### ISSUE TITLE
[Question] How do I only fetch a few lines of information? 

### ISSUE THREAD

**Issue by EthanLeitch** [Macchina-CLI/macchina#253]
I only want to fetch certain lines of information, such as OS, CPU, and battery. How can I achieve this? I tried removing keys from my theme file, but nothing changed.

**Comment by grtcdr** [comment]
Hi @EthanLeitch,

You can achieve this with the `show` option that is specified in `config.toml`, like so:

```toml
# ...
show = ["OperatingSystem",
        "Processor",
        "Battery"]
```

> I tried removing keys from my theme file, but nothing changed.

The `[keys]` section within your theme's configuration defines the text (label) of the readout.

**Comment by EthanLeitch** [comment]
Thanks!

**Comment by grtcdr** [comment]
You're welcome :)
