### ISSUE TITLE
[Docs] Documentation incorrect

### ISSUE THREAD

**Issue by KingPEPSALT** [Macchina-CLI/macchina#254]
Under the [custom ascii colour](https://github.com/Macchina-CLI/macchina/blob/main/doc/macchina.7.scd#color) section, the example uses `separator_color` however I could only get it to work with `color` so I'm assuimg that color is the correct value.

**Comment by grtcdr** [comment]
Thank you, I'll fix that right away!

**Comment by grtcdr** [comment]
I've went ahead and experimented with the indentation to hopefully achieve a better looking and less code-y manual page.
