### ISSUE TITLE
Wiki's use of $XDG_CONFIG_HOME can be more clear 

### ISSUE THREAD

**Issue by meeas** [Macchina-CLI/macchina#256]
**Describe the bug**
The **Customization** and **Configuration** pages in the wiki mention:

`$XDG_CONFIG_HOME/macchina/ on Linux and the BSDs.`

This is technically correct, but can be confusing since most Linux distributions do not set `$XDG_CONFIG_HOME`.  This will lead many users unfamiliar with $XDG settings trying to echo that in a prompt will not get a response and not know where to put the configs without some Googling around.

I recommend changing both pages to:

`~/.config/macchina/ on Linux and the BSDs. (or $XDG_CONFIG_HOME/macchina/ if set)`

And another point of clarification on the **Customization** page is to mention themes must be placed in individual TOML files inside the `themes/` directory.  The way it is currently stated makes it seem they are configs all in a `themes` file.

**Comment by grtcdr** [comment]
Hi, thank you for taking the time to write this issue out!

I totally agree with you, you may edit the wiki if you'd like.

**Comment by grtcdr** [comment]
Fixed :)

Please let me know if you notice any other areas where the wiki can be improved.

I appreciate you reaching out!
