### ISSUE TITLE
[BUG] Typo in build instructions provided in wiki

### ISSUE THREAD

**Issue by nairvarun** [Macchina-CLI/macchina#257]
**Describe the bug**
There is a minor typo in the build instructions provided in the wiki.

**To Reproduce**
1. Go to the Wiki --> Installation --> Building from source --> [Build for everything else](https://github.com/Macchina-CLI/macchina/wiki/Installation#build-for-everything-else)
2. Typo in the code block under the 'Build' subsection

**Expected behavior**
In the above mentioned section, 
`strip /target/release/macchina` 
should be
`strip ./target/release/macchina`

**Comment by grtcdr** [comment]
Hi! Thank you for reporting this :)

I think we should just omit the leading `/`.

**Comment by grtcdr** [comment]
Fixed. Again, thanks for raising this.

**Comment by nairvarun** [comment]
No worries. Thank you for maintaining this project :) 

Also, I just noticed `/target` occurs in 2 other places.
- 2 lines above where this was as `/target/release/`
- In first line of the next code snippet as `/target/debug/`

Shouldn't be a huge issue tho because these are in just in comments but I thought I'd let you know.

**Comment by grtcdr** [comment]
> No worries. Thank you for maintaining this project :)

Thanks :heart:

> Also, I just noticed /target occurs in 2 other places.

I didn't notice that, I'll fix 'em up.
