### ISSUE TITLE
Modifying keys does nothing on macOS

### ISSUE THREAD

**Issue by MichaelMMeskhi** [Macchina-CLI/macchina#260]
Using a custom theme or default, when removing/adding keys, nothing changes. I still see the same default keys on macOS

<img width="412" alt="Screen Shot 2022-08-02 at 1 11 10 PM" src="https://user-images.githubusercontent.com/13300528/182444512-296f552a-0421-498c-935f-5ff1dc015b6c.png">
<img width="251" alt="Screen Shot 2022-08-02 at 1 11 47 PM" src="https://user-images.githubusercontent.com/13300528/182444594-36cf96a3-af08-4ae6-b592-f1a6d42065f2.png">

**Comment by grtcdr** [comment]
Can you try to reproduce this with the following configuration?

> Create ~/.config/macchina/themes/example.toml and add the following

```toml
[keys]
os = "<Operating System>"
```

> temporarily move the configuration file, as to disable it:

```sh
mv ~/.config/macchina/macchina.toml
```

> in your shell:

```sh
macchina -t example
```

**Comment by MichaelMMeskhi** [comment]
Resulting output:

<img width="165" alt="Screen Shot 2022-08-02 at 1 32 09 PM" src="https://user-images.githubusercontent.com/13300528/182448019-3e600ace-09e2-42e0-a649-82a241fdeb5a.png">

**Comment by grtcdr** [comment]
Then something else might be wrong with your configuration, or the theme you've created, can I have a look at both, in textual form?

**Comment by MichaelMMeskhi** [comment]
`Hydrogen.toml`

```
# Hydrogen

spacing         = 2
padding         = 0
hide_ascii      = true
separator       = ">"
key_color       = "Yellow"
separator_color = "White"

[palette]
type = "Dark"
visible = false

[bar]
glyph           = "ߋ"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = true
visible         = true

[box]
title           = "MacBook λ"
border          = "plain"
visible         = true

[box.inner_margin]
x               = 1
y               = 0

[randomize]
key_color       = false
separator_color = false

[keys]
host            = "Host"
battery         = "Battery"
os              = "OS"
terminal        = "Terminal"
uptime          = "Uptime"
memory          = "Memory"
machine         = "Machine"
resolution      = "Resolution"
cpu_load        = "CPU Load"
cpu             = "CPU"
```

Config file:

```
# Specifies the network interface to use for the LocalIP readout
interface = "wlan0"

# Lengthen uptime output
long_uptime = true

# Lengthen shell output
long_shell = false

# Lengthen kernel output
long_kernel = false

# Toggle between displaying the current shell or your user's default one.
current_shell = true

# Toggle between displaying the number of physical or logical cores of your
# processor.
physical_cores = true

# Themes need to be placed in "$XDG_CONFIG_DIR/macchina/themes" beforehand.
# e.g.:
#  if theme path is /home/foo/.config/macchina/themes/Sodium.toml
#  theme should be uncommented and set to "Sodium"
#
theme = "Hydrogen"

# Displays only the specified readouts.
# Accepted values (case-sensitive):
#   - Host
#   - Machine
#   - Kernel
#   - Distribution
#   - OperatingSystem
#   - DesktopEnvironment
#   - WindowManager
#   - Resolution
#   - Backlight
#   - Packages
#   - LocalIP
#   - Terminal
#   - Shell
#   - Uptime
#   - Processor
#   - ProcessorLoad
#   - Memory
#   - Battery
# Example:
# show = ["Battery", "Memory"]
```

**Comment by grtcdr** [comment]
Your theme and configuration are both working as they should.

Example:
- If I give the `memory` option a value of "My Memory", it is reflected.
- If I remove the option, it is reset back to its default value, i.e. "Memory".

Is this not what you are experiencing?

**Comment by MichaelMMeskhi** [comment]
Okay so I figured it out. I was removing keys in the theme and they were still showing up but I realized I have to edit the `show` option in the config file now it works well. Thank you. Side question, is there a way to include the ASCII logo into the box?

**Comment by grtcdr** [comment]
> Side question, is there a way to include the ASCII logo into the box?

I don't think so, but it has been a long time since I've seriously worked with macchina's codebase. I don't personally recall ever adding this in. Also, if something is neither mentioned in the manpages nor the wiki, then it's not a feature.

> Okay so I figured it out. I was removing keys in the theme and they were still showing up but > I realized I have to edit the show option in the config file now it works well.

Awesome, glad you were able to fix it. Always keep in mind that themes have no effect on macchina's behavior, it's only `macchina.toml` that can do that.
