### ISSUE TITLE
[BUG] Macchina 6.1.4 doesn't report version when running macchina --version

### ISSUE THREAD

**Issue by DannyJJK** [Macchina-CLI/macchina#264]
**Describe the bug**
When running `macchina --version` it simply reports `macchina` on its own without the version number.

**To Reproduce**
1. Run `macchina --version`

**Expected behavior**
Command outputs macchina 6.1.4

**Screenshots**
<img width="693" alt="image" src="https://user-images.githubusercontent.com/11057501/190874690-dc9cd05d-46c3-47b3-8317-a320061e2003.png">

**`macchina --doctor` output**
```
Let's check your system for errors... Here's a summary:

We've collected 18 readouts, including 2 failed read(s) and 1 read(s) which resulted in a warning.
Readout "Packages" failed with message: No packages found — Do you have a package manager installed?
Readout "LocalIP" failed with message: Unable to get local IPv4 address.

1 of the 3 unsuccessful read(s) resulted in a warning:
Readout "Distribution" threw a warning with message: Since you're on macOS, there is no distribution to be read from the system.
```

**System Information**
You don't have to provide this information if you're not comfortable doing so, but it'll help us solve the issue a lot faster.
 - Distribution: N/A
 - Desktop Environment: Aqua
 - Operating System: macOS Monterey 12.6 (21G115)
 - Terminal: wezterm 20220905-102802-7d4b8249
 - Macchina's version: 6.1.4

**Comment by 123marvin123** [comment]
<img width="379" alt="CleanShot 2022-09-17 at 23 45 51@2x" src="https://user-images.githubusercontent.com/7266447/190877385-b6f19b5d-4d7b-47dc-b1c7-d084314739e8.png">
Fixed, thanks for the report
