### ISSUE TITLE
[BUG] Brew packages are displayed +1

### ISSUE THREAD

**Issue by Markos-Th09** [Macchina-CLI/macchina#266]
**Describe the bug**
The total number of homebrew packages including casks, bottles and formulae is also displayed +1. For example if I have 4 packages, they are displayed as 5.

**To Reproduce**
1. Install macchina in macOS
2. Install homebrew
3. Install some homebrew packages
4. Use the macchina program

**Expected behavior**
The total amount of packages should display the actual count

**Screenshots**
<img width="600" alt="Screenshot 2022-09-22 at 14 41 25" src="https://user-images.githubusercontent.com/87304130/191726390-0aacf8e6-91b7-4bab-a9be-4ac3291ed0b6.png">

**`macchina --doctor` output**
<img width="599" alt="Screenshot 2022-09-22 at 14 40 23" src="https://user-images.githubusercontent.com/87304130/191726203-3075c98e-532d-4ff0-9015-558e0aded22d.png">

**System Information**
You don't have to provide this information if you're not comfortable doing so, but it'll help us solve the issue a lot faster.
 - Distribution: none
 - Desktop Environment: Aqua (not an option but whatever)
 - Operating System: macOS
 - Terminal: macOS terminal
 - Macchina's version: 6.1.5

**Comment by grtcdr** [comment]
Can you show me the output of `homebrew list | wc -l`?

**Comment by Markos-Th09** [comment]
> Can you show me the output of `brew list | wc -l`?

Actually I used a different command which also shows bottles (dependencies) which I assumed it was also counting

**Comment by Markos-Th09** [comment]
I just actually self solved the problem. There seems to also be a `.keepme` file along the packages

**Comment by grtcdr** [comment]
Hmm, I thought we ignored any ".keepme"s.

This is an easy fix :)

I'll also subtract the result by one.

**Comment by Markos-Th09** [comment]
> Ok although imo the more correct solution fix would be to also check if the .keepme is there first

**Comment by Markos-Th09** [comment]
Also unrelated but I just noticed it isn't showing anything from cargo

**Comment by Markos-Th09** [comment]
Moving this to libmacchina
