### ISSUE TITLE
[BUG] Custom theme not being used

### ISSUE THREAD

**Issue by Lovasz-Akos** [Macchina-CLI/macchina#269]
**Describe the bug**
Weirdly when I specify my custom theme to be used, macchina ignores it and uses default. Extra confusing that the same theme works perfectly on my laptop.

**To Reproduce**
ran
`macchina --theme "E:\Repos\ConfigPool\terminal\Naara.toml"`
(yes the file does exist)

**Expected behavior**
Would expect it to display according to my theme

**Screenshots**
I get the default look:
![image](https://user-images.githubusercontent.com/55391231/196026500-1a46454a-9044-4e2b-a9df-eb9f2f85c243.png)

Instead of my custom, that would look like this:
![image](https://user-images.githubusercontent.com/55391231/196026528-47540ee6-633a-4cbf-ae4f-1eac96ff96e0.png)

**`macchina --doctor` output**
![image](https://user-images.githubusercontent.com/55391231/196026553-5f1c8536-4029-48ad-af77-cc443bcdedc3.png)

**System Information**
You don't have to provide this information if you're not comfortable doing so, but it'll help us solve the issue a lot faster.
 - Distribution: Windows 10
 - Desktop Environment Windows 10 :)
 - Operating System Windows 10 :)
 - Terminal: Windows Terminal (PowerShell)
 - Macchina's version macchina 6.1.6 (118df12) libmacchina 6.3.0

**Comment by grtcdr** [comment]
Hi there,

It's because you're specifying the whole path of theme, whereas `--theme` expects as an argument just the filename of the theme withou the `toml` extension, so "Naara" in your case.

Just be sure to place the theme in the proper directory :)

**Comment by Lovasz-Akos** [comment]
damn, I can't believe I didn't try that, thanks

**Comment by grtcdr** [comment]
No problem, the manpage doesn't specify exactly what the argument should be, but I'll fix that.
