### ISSUE TITLE
Accept disk path(s) to display usage of specified disk / multiple disks

### ISSUE THREAD

**Issue by Rolv-Apneseth** [Macchina-CLI/macchina#286]
I have most of the code for this feature done, but I'll wait for the `libmacchina` crate to be updated to `8.0.0` so it can accept the paths.

My current approach is to add a new option called `disks` which can be used like this in the config:

```toml
disks = ["/", "/home/user"]
```

Or like this as an argument:

```bash
--disks '/,/home/user/'
```

Note that the `show` option of `DiskSpace` would still be required, as otherwise `disks` won't do anything. I did it this way to avoid a rewrite of how the `show` values are currently handled. The other way I thought of doing this was making `show` into an array of tables but that seems overly complicated and it's a breaking change to everyone's configs. What do you think of the approach I took / did I maybe miss a simpler approach?

**Comment by Rolv-Apneseth** [comment]
Checked it out again briefly and - did the code from Macchina-CLI/libmacchina#156 get reverted? I would need that, or something like that, for this feature as otherwise `/` is hard coded. I believe that's why I mentioned here about waiting for `8.0.0` as that was a breaking change

**Comment by grtcdr** [comment]
It wasn't reverted, I think I just moved the `v8` stuff to its own branch, `8.0.0`. We will eventually merge 8.0.0 onto master again, would you mind working against that branch?

**Comment by Rolv-Apneseth** [comment]
Ah, I see, my bad. Yes I can do that
