### ISSUE TITLE
[BUG] Add Debian point releases from /etc/debian_version

### ISSUE THREAD

**Issue by superbonaci** [Macchina-CLI/macchina#291]
Debian stores point releases in another file:
```
$ neofetch
OS: Debian GNU/Linux 12 (bookworm) x86_64
```
```
$ cat /etc/debian_version 
12.1
```
So displaying minor version 12.1 would improve accuracy.
[[Solved] Bookworm upgrade to 12.1](https://forums.debian.net/viewtopic.php?t=155402)

**Comment by superbonaci** [comment]
Reported to original project https://github.com/dylanaraps/neofetch/issues/2381

**Comment by grtcdr** [comment]
This is an upstream issue (or not, depending on how you look at it, but it's definitely not ours).

Adding special exceptions for certain distributions would be a maintenance burden I would *really, really* like to avoid, [/etc/os-release](https://www.freedesktop.org/software/systemd/man/latest/os-release.html) is a widely-adopted standard/convention/whatever and we currently rely on that as a generic mechanism to query distribution information.
