### ISSUE TITLE
[BUG] macOS Sonoma is shown as 'macOS 14.0.0 Unknown'

### ISSUE THREAD

**Issue by caraar12345** [Macchina-CLI/macchina#294]
**Describe the bug**
macOS Sonoma is shown as `macOS 14.0.0 Unknown`. 
*This has been fixed in libmacchina so should be a quick fix*: https://github.com/Macchina-CLI/libmacchina/pull/163

**To Reproduce**
1. Install `macchina` on macOS Sonoma and run it
2. ???
3. Profit

**Expected behavior**
macOS version should show as `macOS 14.0.0 Sonoma`.

**Screenshots**
<img width="882" alt="Screenshot 2023-09-27 at 12 39 03" src="https://github.com/Macchina-CLI/macchina/assets/6129428/fff194a3-ec65-42af-8cda-ef2bfd8aadc7">

**`macchina --doctor` output**

```
❯ macchina -d -i en0
Let's check your system for errors... Here's a summary:

We've collected 18 readouts, including 0 failed read(s) and 1 read(s) which resulted in a warning.
🎉 You are good to go! No failures detected.

1 of the 1 unsuccessful read(s) resulted in a warning:
Readout "Distribution" threw a warning with message: Since you're on macOS, there is no distribution to be read from the system.
```

**System Information**
You don't have to provide this information if you're not comfortable doing so, but it'll help us solve the issue a lot faster.
 - Operating System: macOS
 - Version: Sonoma 14.0.0
 - Terminal: iTerm2
 - Macchina's version: 
   -  macchina     6.1.8
   - libmacchina  6.3.5

**Comment by karimlevallois** [comment]
How would we go about updating its version? I have machine installed through brew.

**Comment by grtcdr** [comment]
Unless a new version comes out, macchina will continue to report that field as it currently does. I can't say for sure when a new version will arrive.

**Comment by karimlevallois** [comment]
> Unless a new version comes out, macchina will continue to report that field as it currently does. I can't say for sure when a new version will arrive.

So we cannot upgrade libmacchina on its own then?

**Comment by grtcdr** [comment]
I'm afraid not. You can, in the meantime, [build the program from source](https://github.com/Macchina-CLI/macchina/wiki/Installation#build-for-everything-else) to get around the issue.

**Comment by karimlevallois** [comment]
> I'm afraid not. You can, in the meantime, [build the program from source](https://github.com/Macchina-CLI/macchina/wiki/Installation#build-for-everything-else) to get around the issue.

Ah OK, would probably wait then. Is there no way for us to override what it says? Like a custom string in a file?

**Comment by grtcdr** [comment]
I don't know if we wan't to include that level of customization. macchina is, after all, supposed to automate the collection and display process. You can temporarily hide that specific readout by listing every other one and explicitly omitting it from the `show` list in your `macchina.toml`.

**Comment by mikemadden42** [comment]
A recent version of macchina detects macOS correctly.  I'd built this version from source.

```
$ macchina --version
macchina     6.2.0
libmacchina  7.2.1
```

```
macOS 14.4.1 Sonoma
```

**Comment by grtcdr** [comment]
As @mikemadden42 has shown, the issue was fixed upstream, it shouldn't be a problem in a future release. I'll close this issue then.
