### ISSUE TITLE
[BUG] Macchina errors for me when using the provided macchina.toml

### ISSUE THREAD

**Issue by ColetteDiskette** [Macchina-CLI/macchina#298]
**Describe the bug**
Macchina runs fine until I create a macchina.toml in `~/.config/macchina`, at which time I get the message:
```
Error: At line 1 column 1.
Caused by: unknown field `memory_percentage`, expected one of `show`, `long_uptime`, `long_shell`, `long_kernel`, `physical_cores`, `current_shell`, `theme`, `interface` at line 1 column 1
```

This happens to me even just copying the macchina.toml from the git to the Macchina config directory.

**To Reproduce**
1. Place an existing macchina.toml or create a macchina.toml in `~/.config/macchina`.
2. Run Macchina.

**Expected behavior**
Macchina to run properly using the config file without error.

**`macchina --doctor` output**
```
Error: At line 1 column 1.
Caused by: unknown field `memory_percentage`, expected one of `show`, `long_uptime`, `long_shell`, `long_kernel`, `physical_cores`, `current_shell`, `theme`, `interface` at line 1 column 1
Let's check your system for errors... Here's a summary:

We've collected 18 readouts, including 4 failed read(s) and 1 read(s) which resulted in a warning.
Readout "OperatingSystem" failed with message: This metric is not available on this platform or is not yet implemented by libmacchina.
Readout "LocalIP" failed with message: Unable to get local IPv4 address.
Readout "Backlight" failed with message: Could not obtain backlight information.
Readout "Battery" failed with message: No batteries detected.

1 of the 5 unsuccessful read(s) resulted in a warning:
Readout "DesktopEnvironment" threw a warning with message: You appear to be only running a window manager.
```

**System Information**
 - Distribution: Debian (testing branch)
 - Desktop Environment: None. (Running awesomewm.)
 - Terminal: Alacritty
 - Macchina 6.1.8
 - libmacchina 6.4.1
 - Installed through cargo package

**Comment by grtcdr** [comment]
That option hasn't landed yet, removing it should fix the problem.

**Comment by ColetteDiskette** [comment]
Okay, commenting out "memory_percentage" and "disk_space_percentage" fixed it. Solved for me! I appreciate the quick response.
