### ISSUE TITLE
-o isn't working properly 

### ISSUE THREAD

**Issue by Magniquick** [Macchina-CLI/macchina#299]
**Describe the bug**
-o is outputting (error: Found argument 'Kernel' which wasn't expected, or isn't valid in this context)

**To Reproduce**
1. run ```❯ macchina --theme Beryllium -o Host Kernel Distribution Packages DesktopEnvironment Memory ProcessorLoad Shell Terminal WindowManager Battery```
2. errors out with: 
```
error: Found argument 'Kernel' which wasn't expected, or isn't valid in this context
Usage: macchina [OPTIONS]
For more information try '--help'
```

**Expected behavior**
proper output

**Screenshots**
<img width="772" alt="Screenshot 2023-12-30 at 8 14 00 PM" src="https://github.com/Macchina-CLI/macchina/assets/67406856/c5e02c2c-544d-44ff-bb73-b1e0a7c3f8e5">

**`macchina --doctor` output**
```
❯ macchina --doctor
Let's check your system for errors... Here's a summary:

We've collected 18 readouts, including 2 failed read(s) and 1 read(s) which resulted in a warning.
Readout "LocalIP" failed with message: Unable to get local IPv4 address.
Readout "Battery" failed with message: Dictionary does not contain information about the battery. Are you using a third-party battery?

1 of the 3 unsuccessful read(s) resulted in a warning:
Readout "Distribution" threw a warning with message: Since you're on macOS, there is no distribution to be read from the system.
```

**System Information**
You don't have to provide this information if you're not comfortable doing so, but it'll help us solve the issue a lot faster.

 - Operating System: macos
 - Terminal: iTerm2
 - Macchina's version
 ```
 ❯ macchina --version
macchina     6.1.8
libmacchina  6.3.5
```

**Comment by grtcdr** [comment]
Fixed, thanks for reporting!

**Comment by Magniquick** [comment]
> @grtcdr 
> Fixed, thanks for reporting!

Just built from source, still seems to be broken
<img width="940" alt="Screenshot 2023-12-31 at 2 13 10 PM" src="https://github.com/Macchina-CLI/macchina/assets/67406856/d648a772-c837-4576-9033-437952d98936">

**Comment by grtcdr** [comment]
That's really weird, it seems to work for me (casing is different however, this issue should be addressed separately).

![2023-12-31T12:45:12,684528323+01:00](https://github.com/Macchina-CLI/macchina/assets/35816711/b4ae53a8-68ff-4fb6-a0d8-a38fe84e05d3)

**Comment by Magniquick** [comment]
> That's really weird, it seems to work for me (casing is different however, this issue should be addressed separately).

Comma seperation along with leaving no spaces work, thanks !

**Comment by grtcdr** [comment]
I forgot to mention that multiple arguments to a flag require a delimiter. Glad to hear it's working.
