### ISSUE TITLE
[Feature Request] Image support like Neofetch.

### ISSUE THREAD

**Issue by helixoid** [Macchina-CLI/macchina#304]
I wish that I could use some image in my macchina output instead of ascii characters.
It really helps with the customization perspective.

I really don't want to use neofetch after using macchina as it is blazing fast and I am also replacing most of my system components with their rust counterparts.

```
$ time neofetch

Executed in  539.08 millis    fish           external
   usr time  351.07 millis  266.00 micros  350.81 millis
   sys time  168.14 millis  133.00 micros  168.01 millis
```

```
$ time macchina

Executed in   11.91 millis    fish           external
   usr time    5.58 millis  338.00 micros    5.24 millis
   sys time    2.68 millis   65.00 micros    2.62 millis
```

**Comment by grtcdr** [comment]
Hi, I don't personally see myself using or interested in maintaining such a feature, and since there hasn't been any interest from the community either, I will be closing it.
