### ISSUE TITLE
[FEATURE] Palette spacing

### ISSUE THREAD

**Issue by feefs** [Macchina-CLI/macchina#307]
Would there be interest in adding a palette.spacing option? For context, I like my palette glyphs to be spaced out. However, setting palette.glyph to "色    " results in the block not respecting the line length:
<img width="476" alt="1" src="https://github.com/Macchina-CLI/macchina/assets/25848712/ef282501-e3cb-4ddd-b0f3-20da4f2be752">

I've implemented a version locally, which adds "spacing" to the [palette] options in the toml ([example location](https://github.com/Macchina-CLI/macchina/blob/a10f908dc02dc4b668ee96b43c666b6b05a63698/contrib/themes/Beryllium.toml#L13))
<img width="471" alt="2" src="https://github.com/Macchina-CLI/macchina/assets/25848712/44e2593d-617c-48e6-80c6-4dde89c5da60">

If there's interest, I can open a PR.

**Comment by grtcdr** [comment]
Hi, thanks for working on this. I'd definitely like to see this get merged.
