### ISSUE TITLE
Investigate CI failure of NetBSD cross-compilation

### ISSUE THREAD

**Issue by grtcdr** [Macchina-CLI/macchina#312]
The build job of our CI pipelines providing cross-compilation to NetBSD has started failing since 3c51e5b2738c0de72fce525564651ccb88272236 for no apparent reason.

**Comment by FantasyTeddy** [comment]
As mentioned in #311, the issue has been fixed in cross-rs/cross#1348 and would be resolved with this PR.

**Comment by grtcdr** [comment]
Ah, great, thanks for the info!

**Comment by grtcdr** [comment]
#311 fixed this.
