### ISSUE TITLE
Only Include Certain Keys

### ISSUE THREAD

**Issue by s4Dt0y** [Macchina-CLI/macchina#314]
Is there a way to not have certain keys? This seems like a really dumb question, but I haven't been able to figure out a way...simply not including it in the keys category doesn't seem to work. Is there a way to do this, like, an `only_explicit_includes` variable? I took a look at #222, and it seems like people have been able to this.

**Comment by grtcdr** [comment]
Use the `--show` flag or `show` option in `macchina.toml`, it is documented in the [man page](https://github.com/Macchina-CLI/macchina/blob/main/doc/macchina.1.scd#flags).
