### ISSUE TITLE
[Windows] Customization feature request

### ISSUE THREAD

**Issue by zerox003** [Macchina-CLI/macchina#318]
Nice to have for customization: 
- spacer 

literally just spacer to organize the output e.g:
```
GPU > output
-----------------
DiskSpace > output
``` 

- customize Bar spacing

`/ / / / / / / /` -> `///////////` or `/  /  /  /  /  /`

**Comment by grtcdr** [comment]
We're [no longer accepting feature requests](https://github.com/Macchina-CLI/macchina?tab=readme-ov-file#status), sorry.
