### ISSUE TITLE
[Linux] Cannot display GPU info

### ISSUE THREAD

**Issue by hruboson** [Macchina-CLI/macchina#322]
**Describe the bug**
Cannot display GPU info. 

I'm a bit confused because the wiki ([toml example](https://github.com/Macchina-CLI/macchina/blob/main/macchina.toml)) says macchina can display GPU info, but when I try to display it, an error pops up saying: 
```
Error: At line 1 column 1.
Caused by: unknown variant 'GPU', expected one of 'Host', 'Machine', 'Kernel', 'Distribution', 'OperatingSystem', 'DesktopEnvironment', 'WindowManager', 'Packages', 'Shell', 'Terminal', 'LocalIP', 'Backlight', 'Resolution', 'Uptime', 'Processor', 'ProcessorLoad', 'Memory', 'Battery' for key `show` at line 1 column 1
```

**To Reproduce**
1. Download prebuilt binary (macchina-linux-x86_64 released 9 Jan 24)
2. Run the binary with `-o GPU` or specify `"GPU"` option in `show` in configuration file.

**Expected behavior**
Macchina shows GPU info.

**`macchina --doctor` output**
 ```
Error: At line 1 column 1.
Caused by: unknown variant 'GPU', expected one of 'Host', 'Machine', 'Kernel', 'Distribution', 'OperatingSystem', 'DesktopEnvironment', 'WindowManager', 'Packages', 'Shell', 'Terminal', 'LocalIP', 'Backlight', 'Resolution', 'Uptime', 'Processor', 'ProcessorLoad', 'Memory', 'Battery' for key `show` at line 1 column 1
Let's check your system for errors... Here's a summary:

We've collected 18 readouts, including 4 failed read(s) and 0 read(s) which resulted in a warning.
Readout "OperatingSystem" failed with message: This metric is not available on this platform or is not yet implemented by libmacchina.
Readout "WindowManager" failed with message: Unknown window manager.
Readout "LocalIP" failed with message: Unable to get local IPv4 address.
Readout "Battery" failed with message: Got an unexpected value "not charging" reading battery status 
```

**System Information**
 - Distribution: Fedora 40
 - Desktop Environment: KDE Plasma
 - Operating System: Linux
 - Terminal: Kitty
- Version: 
    - macchina     6.1.8 (f228e72)
    - libmacchina  6.3.5

**Comment by grtcdr** [comment]
Hi, that readout was added in `libmacchina` v7.0.0, it's unfortunately a mistake in the documentation to have included that as a possible readout since the current release of `macchina` is still on `libmacchina` v6.x. If you don't mind getting your hands dirty, you can compile the software from source to utilize that readout until a new release comes out.

**Comment by hruboson** [comment]
Okay, thanks for the info, will try to do that
