### ISSUE TITLE
No LocalIP on Alpine

### ISSUE THREAD

**Issue by OH016** [Macchina-CLI/macchina#335]
**Describe the bug**

Unable to get local IPv4 address.

**`macchina --doctor` output**
Add a screenshot or copy and paste the output of `--doctor` if an element you're supposed to be seeing isn't showing up.
![image](https://github.com/user-attachments/assets/ceb82273-99b1-4d56-bf7a-47618e92351e)

**Comment by grtcdr** [comment]
I can also confirm this on a fresh Alpine container (macchina installed from edge repository).

**Comment by cooocy** [comment]
You must set up your network interface in the configuration file to display the IP address correctly.
The demo configuration file is [macchina.toml](https://github.com/Macchina-CLI/macchina/blob/main/macchina.toml)
And set up this.
```
interface = "wlan0"
```
You can see your network interface using `ifconfig` or `ipconfig`.
Like this:
<img width="762" alt="image" src="https://github.com/user-attachments/assets/1f2df8e1-40f5-498d-9777-a3f2f2109d84">
<img width="632" alt="image" src="https://github.com/user-attachments/assets/85e19109-1c6b-48ea-989a-f866854ec217">

**Comment by grtcdr** [comment]
@cooocy *(well duh)* how did the `interface` option not cross my mind as the first thing to recommend for @OH016 to check?

Thanks for pointing that out.
