### ISSUE TITLE
[Documentation Improvements] Wrong key `LocalIp` in example file `macchina.toml`

### ISSUE THREAD

**Issue by cooocy** [Macchina-CLI/macchina#337]
**Describe the bug**
I don't think this is a bug, but an improvement in the documentation.
In the example configuration file https://github.com/Macchina-CLI/macchina/blob/main/macchina.toml ,`LocalIP` was mistakenly written as `LocalIp`.
<img width="407" alt="image" src="https://github.com/user-attachments/assets/033fb9ff-fef1-4042-a3ac-17c29feafda8">
I think if this document is improved, it may be helpful to novice users.

**Expected behavior**

**Screenshots**
<img width="1196" alt="image" src="https://github.com/user-attachments/assets/bb5216b8-1c40-47ad-902d-8a32e8c4e69b">

This is a very, very minor issue, and I can provide assistance if you think it is necessary to make a modification.

**Comment by grtcdr** [comment]
Oh good catch, I'll accept a PR if you'd like to contribute this change yourself :)

**Comment by cooocy** [comment]
🎉 Fixed.
