### ISSUE TITLE
[BUG] Misinformations in macOS version.

### ISSUE THREAD

**Issue by ftpd** [Macchina-CLI/macchina#47]
**Describe the bug**
There are some false information when running macchina on macOS:
1) "OS        —  macOS 10.16.0 Big Sur" - Big Sur is actually version 11.
2) "Packages  —  7" - I don't know how it's getting this info, but for me it's false - I have 6 packages installed from brew. I did a very simple test and installed one more, so now macchina shows 8. So, there is +1 difference.
3) "Terminal  —  xterm-256color" - it's not a bug, more like feature request: it would be better to see terminal emulator (built-in Terminal, iTerm2, Alacritty and so on), as now it shows the value of $TERM.

**To Reproduce**
1. run macchina.

**Expected behavior**
Proper info.

**System Information**
 - Distribution: macOS 11.2.3
 - Desktop Environment: Aqua
 - Terminal: iTerm2
 - Macchina's version: 0.6.0

**Comment by grtcdr** [comment]
Hi, thanks for reporting these issues!

@123marvin123  should be able to look into them as support for **macOS** was introduced completely by him. 
But in the meantime, I'll take a look and see if I can fix them.

**Comment by ftpd** [comment]
Thank you!

If you need more help with testing, feel free to contact me. I know nothing about coding in Rust, but I know macOS pretty well and I'll be glad to help as much as possible.

**Comment by grtcdr** [comment]
> Thank you!
> 
> If you need more help with testing, feel free to contact me. I know nothing about coding in Rust, but I know macOS pretty well and I'll be glad to help as much as possible.

You're welcome! I didn't mention the third point but terminal fetching will probably evolve to no longer use $TERM on macOS.

**Comment by 123marvin123** [comment]
> **Describe the bug**
> There are some false information when running macchina on macOS:
> 
> 1. "OS        —  macOS 10.16.0 Big Sur" - Big Sur is actually version 11.
> 2. "Packages  —  7" - I don't know how it's getting this info, but for me it's false - I have 6 packages installed from brew. I did a very simple test and installed one more, so now macchina shows 8. So, there is +1 difference.
> 3. "Terminal  —  xterm-256color" - it's not a bug, more like feature request: it would be better to see terminal emulator (built-in Terminal, iTerm2, Alacritty and so on), as now it shows the value of $TERM.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. run macchina.
> 
> **Expected behavior**
> Proper info.
> 
> **System Information**
> 
> * Distribution: macOS 11.2.3
> * Desktop Environment: Aqua
> * Terminal: iTerm2
> * Macchina's version: 0.6.0

1. If you downloaded the binary from the GitHub release page, you get this phenomenon because the GitHub-provided runner that builds it is still running Catalina and reports Big Sur as 10.16. After GitHub updated the runner, we will see the report as 11.2.*. If it bothers you, I can upload a binary built on Big Sur.
2. At the moment, Macchina is counting the amount of directories in the Homebrew directory because I have not yet understood how they are booking the installed packages. I don’t want to invoke the „brew“ command from Macchina because it is really slow.
3. Yes, it’s currently on the todo list :)

**Comment by ftpd** [comment]
1. No problem, I will wait.
2. Where are you counting them? Maybe something like `ls -1 /usr/local/Cellar | wc -l` will work? It gives the correct number.
3. Great ;-)

**Comment by 123marvin123** [comment]
It counts the folders in /usr/local/Cellar and Caskroom, but I think this will give a false reading info your load a package from a different Tap.

**Comment by grtcdr** [comment]
Is this an issue still or should I close this?

**Comment by grtcdr** [comment]
A workaround was implemented a while ago by @123marvin123 that addresses the terminal issue you were having, so I'm closing this for now.
