### ISSUE TITLE
Display Ubuntu nickname

### ISSUE THREAD

**Issue by ngirard** [Macchina-CLI/macchina#75]
(Or whatever they call it).
This is something I find myself constantly looking after: Ubuntu releases have a version number (20.04 in my case), *and* a "nickname" (Focal). In many cases I need the latter, and I'm always doubting about which is right.

Granted, I could just `cat /etc/os-release` (which is the now [standard](http://0pointer.de/blog/projects/os-release) way of doing it), but I still need to ponder whether I should `lsb_release`, or `cat /etc/lsb-release` or whatever, and it distracts me from the problem at hand.

Would you add this piece of info to Macchina, I'd adopt it. Deal ?

Cheers, and thanks for your work !

**Comment by grtcdr** [comment]
Deal, can you send me a screenshot of /etc/os-release so I can see which fied contains the nickname?

**Comment by ngirard** [comment]
Sure, I'll even attach a copy if the file to this issue.

But you might not even need it, since there's a [dedicated crate](https://lib.rs/crates/os-release) from the folks behind Pop!OS for parsing this file.

The info I was referring to is contained in the [version](https://docs.rs/os-release/0.1.0/os_release/struct.OsRelease.html#structfield.version) field.

[os-release.zip](https://github.com/Macchina-CLI/macchina/files/6336119/os-release.zip)

**Comment by grtcdr** [comment]
> But you might not even need it, since there's a [dedicated crate](https://lib.rs/crates/os-release) from the folks behind Pop!OS for parsing this file.

We already use it :)

**Comment by ngirard** [comment]
Ah, great, thanks !

How about submitting an issue upstream ? I'm sure they would be glad to fix it !

**Comment by grtcdr** [comment]
> Ah, great, thanks !
> 
> How about submitting an issue upstream ? I'm sure they would be glad to fix it !

I'm sort of busy right now, but I guess I can do it when I find the time.

**Comment by grtcdr** [comment]
Hey there! Cobalt should fix your issue.

Have a great one 🍻

**Comment by ngirard** [comment]
Hehe, indeed, thanks !
Adopted !
```sh
macchina --no-ascii --theme Boron --no-box --bar --box-title "" -X Host -X Machine -X Kernel -X Distribution -X Packages -X LocalIP -X Uptime -X ProcessorUsage -X Memory --spacing 1
```

**Comment by grtcdr** [comment]
> ```shell
> macchina --no-ascii --theme Boron --no-box --bar --box-title "" -X Host -X Machine -X Kernel -X Distribution -X Packages -X LocalIP -X Uptime -X ProcessorUsage -X Memory --spacing 1
> ```

> Hehe, indeed, thanks !
You're welcome :beers: 

There's no need to use -X multiple times, you can use it once like this:
```
macchina -X battery processusage
```

You can also use `--no-title` instead of `--box-title ""`.

**Comment by ngirard** [comment]
> There's no need to use -X multiple times

Thanks for your feedback. It would be worth adding to the CLI help, because intuitively I first tried `-X Package1,Package2` and didn't expect space as a separator.

> You can also use `--no-title` instead of `--box-title ""`.

Noted, thanks !

**Comment by grtcdr** [comment]
> Thanks for your feedback. It would be worth adding to the CLI help, because intuitively I first tried `-X Package1,Package2` and didn't expect space as a separator.

You're right, but once you use one Rust cli tool, they're all very similar, as we all use clap and structopt, and space is by default the options separator.

**Comment by ngirard** [comment]
> once you use one Rust cli tool, they're all very similar, as we all use clap and structopt, and space is by default the options separator.

I'd respectfully disagree ;-) As first counterexample out of my mind: [Navi](https://github.com/denisidoro/navi/issues/461#issuecomment-821801039)

**Comment by grtcdr** [comment]
Notice I said "default", because clap does let you require a delimiter for certain subcommands, but we don't require any delimiters, to let you do what you need to do, without typing as much.
