### ISSUE TITLE
[BUG] macchina CPU% bar is empty when CPU usage is above 100%

### ISSUE THREAD

**Issue by uttarayan21** [Macchina-CLI/macchina#79]
**Describe the bug**
When the cpu usage is above 100% 
`macchina --bar`
Shows cpu% as empty

**To Reproduce**
1. Run some cpu intensive task
2. Run `maccina --bar`

**Expected behavior**
I'd hope to see a full bar instead of an empty bar

**Screenshots**
[macchina](https://user-images.githubusercontent.com/18732700/115909524-43ce4b00-a489-11eb-8b9c-ecd0c8ef8145.png)

![macchina-bar](https://user-images.githubusercontent.com/18732700/115909513-403ac400-a489-11eb-87d0-d2e0e2df8cd1.png)

**`macchina --doctor` output**
Add a screenshot or copy and paste the output of `--doctor` if an element you're supposed to be seeing isn't showing up.

**System Information**
You don't have to provide this information if you're not comfortable doing so, but it'll help us solve the issue a lot faster.
 - Distribution: [e.g. Pop!_OS]
 - Desktop Environment [e.g. Plasma]
 - Operating System [e.g. macOS]
 - Terminal [e.g. Alacritty]
 - Macchina's version [e.g. 0.5.9]

**Comment by grtcdr** [comment]
I can cap the CPU% at 100%, what do you suggest?

**Comment by uttarayan21** [comment]
I'd still like to see how much I'm pushing the CPU in the text but I'd like a full bar with the `--bar` option.

**Comment by grtcdr** [comment]
> I'd still like to see how much I'm pushing the CPU in the text but I'd like a full bar with the `--bar` option.

Ah okay, that makes sense.
