### ISSUE TITLE
[BUG] macchina 0.7.3 test failed

### ISSUE THREAD

**Issue by chenrui333** [Macchina-CLI/macchina#81]
**Describe the bug**

👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>test failure</summary>

```
$ RUST_BACKTRACE=full /usr/local/Cellar/macchina/0.7.3/bin/macchina --doctor
thread 'main' panicked at 'Could not get vm page size.', /Users/rchen/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/libmacchina-0.3.1/src/macos/mod.rs:335:18
stack backtrace:
   0:        0x10772b02f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04abbaabf148650a
   1:        0x1076ff51e - core::fmt::write::h14dac7cadec1cc70
   2:        0x107727e3a - std::io::Write::write_fmt::hfaf2e10dfdcc61d8
   3:        0x10774a313 - std::panicking::rust_panic_with_hook::h8cdc0a575f4a5a7b
   4:        0x10770c8dd - std::panicking::begin_panic::{{closure}}::h1cb5e31eebf53a0a
   5:        0x10770c8a8 - std::sys_common::backtrace::__rust_end_short_backtrace::h5289044154439ad3
   6:        0x10775d93d - std::panicking::begin_panic::ha9aa3db83f8d0fab
   7:        0x10768baf1 - macchina::data::get_all_readouts::h7f00e763b2b7f7aa
   8:        0x10769198e - macchina::main::h3272ae73cea80bf8
   9:        0x10767b3ca - std::sys_common::backtrace::__rust_begin_short_backtrace::h0fecb7c939f513a5
  10:        0x10767bb96 - std::rt::lang_start::{{closure}}::h0cc748e43438e7c3
  11:        0x1076a9819 - _main
```

</details>

Full build log is in here, https://github.com/Homebrew/homebrew-core/runs/2488142444
relates to https://github.com/Homebrew/homebrew-core/pull/76473

**Comment by grtcdr** [comment]
This is genuinely a weird bug, I'm glad I know where it stems from, but I can't seem to wrap my head around why it's occurring.

There was a build error that first appeared on macOS in version 0.7.0 that I didn't quite notice, and I resolved it by changing the type of the `page_size`, which receives its value from the sysctl `hw.pagesize` entry.

I'll investigate this further and roll out a fix as soon as I can.

**Comment by chenrui333** [comment]
Thanks @grtcdr!

**Comment by grtcdr** [comment]
Hey @chenrui333, so I got down to the bottom of it, and these sort of build errors should be a thing of the past, as our actions have switched from testing, to using --doctor, to ensure that no panics happen.

A release will come out in a little bit.

See you!

**Comment by chenrui333** [comment]
yeah, got successfully upgraded, https://github.com/Homebrew/homebrew-core/pull/76559
