### ISSUE TITLE
[Question] About the creation of a configuration file

### ISSUE THREAD

**Issue by PandaFoss** [Macchina-CLI/macchina#83]
By default `macchina` displays all system information in a default format. To change this, one must make use of the many options available (and there seem to be more and more of them). And this can sometimes result in a rather long command.

I'm not sure what the future plans of the project are, but it occurs to me that creating a configuration file from which to read the `macchina` defaults might be a good idea. Of course this is not the only way to solve the above problem; on Linux systems you could create an `alias` that runs `macchina` with the desired options.

I have also tried the different themes offered by the application. My question is, are there any plans to add custom themes? It could be an alternative to the configuration file.

Of course, whichever way you go, it's not something that will be done overnight. But whatever I can do to help, I'm willing.

**Comment by uttarayan21** [comment]
This should be easy if we use [`serde`](https://serde.rs).  
Maybe a `.toml` configuration option will be for the best ?.  
Adding a `#[derive(Deserialize)]` to the `Opt` struct and building an object from a config file will be easy.
The more difficult part would be to implement the priority i.e. commandline -> config -> defaults.
 
I was actually looking into this a while back.

**Comment by PandaFoss** [comment]
> We can use [`dirs-rs`](https://github.com/dirs-dev/dirs-rs) to store the config file at correct locations .

I think `dirs-rs` might be a good option (I didn't know that crate). We could even read an environment variable (e.g. `MACCHINA_CONF`) in case the user wants to place the configuration file somewhere else.

>  Maybe a `.toml` configuration option will be for the best ?.

On this, I think it is a good option. It is widely used in the Rust environment, and has the advantage that it is relatively easy to understand for a non-experienced user (unlike, for example, JSON).

**Comment by grtcdr** [comment]
@uttarayan21 Brilliant :smile:

**Comment by grtcdr** [comment]
How does it handle unexpected values?

**Comment by uttarayan21** [comment]
> @uttarayan21 Brilliant 😄

Thanks :)

> How does it handle unexpected values?

It just stops reading the file and returns Opt::default().
It still needs more work since an incomplete config file will panic.

I'm also adding a --export-config that will print a `toml` file to stdout based on the rest of the commandline options.

**Comment by grtcdr** [comment]
> It just stops reading the file and returns Opt::default().

That's good, I think a great addition is to reference the state of the config file in `--doctor` 

> I'm also adding a --export-config that will print a `toml` file to stdout based on the rest of the commandline options.

Awesome, that's a great feature :)

**Comment by uttarayan21** [comment]
> That's good, I think a great addition is to reference the state of the config file in --doctor

I was actually thinking of how to achieve that but currently I have no idea how to do that.
I made a `impl Opt { pub fn from_config() -> Opt {...} }` so as to have similar name to `Opt::from_args`.

So I can 
- return `Result<Opt,Error>` and handle the default stuff in main.
- return `Result<(Opt,bool),Error>` where the bool is whether the config read failed.

I'm more inclined towards the first option.

**Comment by grtcdr** [comment]
This sort of makes more sense than the `--doctor` option, because `--doctor` handles readouts and might require some tweaking in order to get the state of the config in there as well.

**Comment by uttarayan21** [comment]
So I guess we can display a warning before the tui is initialized.

**Comment by grtcdr** [comment]
That might be annoying to some, we might consider adding a new flag that checks if the config exists in the appropriate path, and if (and where) any errors have occurred.

**Comment by uttarayan21** [comment]
> That might be annoying to some,

True, but if you have a malformed config file any program will show a warning first and foremost or outright refuse to function.
Warning will only show *if* there is a malformed config, not if there is no config or a correct config.

**Comment by grtcdr** [comment]
> True, but if you have a malformed config file any program will show a warning first and foremost or outright refuse to function.
> Warning will only show _if_ there is a malformed config, not if there is no config or a correct config.

You do raise a good point about most programs showing warnings of an incorrect config file, but I'd really love to see what @PandaFoss thinks about this.

I for one think that there's a certain group of users who might be turned away from the program when they're presented with a warning, but as you've pointed out, it might be more helpful to display such a warning.

**Comment by uttarayan21** [comment]
> I for one think that there's a certain group of users who might be turned away from the program when they're presented with a warning, but as you've pointed out, it might be more helpful to display such a warning.

I see your point but I have a counter argument.
The config is not there by default, only when the user exports a config and modifies it manually with wrong values only then the warning is shown. By this point I think showing a warning is justified since `macchina` will also run will default values after the warning is shown.

**Comment by uttarayan21** [comment]
Oh I didn't mean a blocking warning.
I meant something like this.
![warn](https://user-images.githubusercontent.com/18732700/117534864-d8e84c80-b010-11eb-9901-703593a265ec.png)

**Comment by grtcdr** [comment]
Will we be adding where errors occur? If so, the warning might get a bit too long...

**Comment by uttarayan21** [comment]
Adding where the errors occur might be a bit difficult for me as of now. Since I don't have in depth understanding of how serde deserialization occurs.

**Comment by grtcdr** [comment]
> Adding where the errors occur might be a bit difficult for me as of now. Since I don't have in depth understanding of how serde deserialization occurs.

That's okay, we'll add it another time.
