### ISSUE TITLE
[Info] Macchina in Termux

### ISSUE THREAD

**Issue by PandaFoss** [Macchina-CLI/macchina#84]
I have [added Macchina as a package](https://github.com/termux/termux-packages/pull/6744) in Termux, so it can now be installed on Android through Termux with the `apt` package manager:

`apt install macchina`

<a href="https://ibb.co/WD79NyK"><img src="https://i.ibb.co/vsf5CPz/photo-2021-05-05-19-19-14.jpg" alt="photo-2021-05-05-19-19-14" border="0"></a>

If you wish I can edit the [Wiki](https://github.com/Macchina-CLI/macchina/wiki/Installation) to add the Termux installation option.

Edit: You can close the issue when you see it, it is for information purposes only.

**Comment by grtcdr** [comment]
This is wonderful news, thank you!

> If you wish I can edit the Wiki to add the Termux installation option.

Yeah, feel free to include it :)
