### ISSUE TITLE
[question] raspberry slow on cargo (rust?!)

### ISSUE THREAD

**Issue by Dan1jel** [Macchina-CLI/macchina#89]
When trying to install on my Raspberry, my pi is throttling the cargo installation. All 4 core go on 100% load and becomes very slow on installing. is there any easier way? im thinking "pkg install macchina".

**Comment by grtcdr** [comment]
Building Rust code from source is usually like that, I recommend you download and run the prebuilt binaries that you can find in the releases page.

**Comment by Dan1jel** [comment]
> Building Rust code from source is usually like that, I recommend you download and run the prebuilt binaries that you can find in the releases page.

Ok, that could work, i mean its not the easiest but as long as it works. But for a newbie like me, how do i build from binaries? i tried to search the web but all i can think of is "cargo install" but that will make my Raspberry throttle (and probably fail the install).

**Comment by grtcdr** [comment]
> Ok, that could work, i mean its not the easiest but as long as it works. But for a newbie like me, how do i build from binaries? i tried to search the web but all i can think of is "cargo install" but that will make my Raspberry throttle (and probably fail the install).

The [releases page](https://github.com/Macchina-CLI/macchina/releases/tag/v0.7.4) has prebuilt binaries, meaning source code that was built and can be used directly, you mentioned you're on trying to run macchina for you Raspberyy Pi, so you can click the `macchina-linux` link which will download the binary for you, and all you have to do is `chmod +x macchina-linux` to give it execute permissions.

After doing that, just run `./macchina-linux` or place it in your `PATH` e.g. in **~/.local/share** or **/usr/bin/** which will then allow you to run it from anywhere on your system.

`cargo install` looks through the **crates.io** registry and builds the package you're looking for from source, meaning your CPU is going to be running at full throttle until the build process is finished.

**Comment by Dan1jel** [comment]
> > Ok, that could work, i mean its not the easiest but as long as it works. But for a newbie like me, how do i build from binaries? i tried to search the web but all i can think of is "cargo install" but that will make my Raspberry throttle (and probably fail the install).
> 
> The [releases page](https://github.com/Macchina-CLI/macchina/releases/tag/v0.7.4) has prebuilt binaries, meaning source code that was built and can be run directly, you mentioned you're on trying to run macchina for your Raspberyy Pi, so you can click the `macchina-linux` link which will download the binary for you, and all you have to do is `chmod +x macchina-linux` to give it execute permissions.
> 
> After doing that, just run `./macchina-linux` or place it in your `PATH` e.g. in **~/.local/share** or **/usr/bin/** which will then allow you to run it from anywhere on your system.
> 
> `cargo install` looks through the **crates.io** registry and builds the package you're looking for from source, meaning your CPU is going to be running at full throttle until the build process is finished.

Thank you so much for the great explinaton. But when i try this, all i get is -

` ~ $ ./macchina-linux
Failed to execute process './macchina-linux'. Reason:
exec: Exec format error
The file './macchina-linux' is marked as an executable but could not be run by the operating system.`

**Comment by grtcdr** [comment]
> > > Ok, that could work, i mean its not the easiest but as long as it works. But for a newbie like me, how do i build from binaries? i tried to search the web but all i can think of is "cargo install" but that will make my Raspberry throttle (and probably fail the install).
> > 
> > 
> > The [releases page](https://github.com/Macchina-CLI/macchina/releases/tag/v0.7.4) has prebuilt binaries, meaning source code that was built and can be run directly, you mentioned you're on trying to run macchina for your Raspberyy Pi, so you can click the `macchina-linux` link which will download the binary for you, and all you have to do is `chmod +x macchina-linux` to give it execute permissions.
> > After doing that, just run `./macchina-linux` or place it in your `PATH` e.g. in **~/.local/share** or **/usr/bin/** which will then allow you to run it from anywhere on your system.
> > `cargo install` looks through the **crates.io** registry and builds the package you're looking for from source, meaning your CPU is going to be running at full throttle until the build process is finished.
> 
> Thank you so much for the great explinaton. But when i try this, all i get is -
> 
> ` ~ $ ./macchina-linux`
> `Failed to execute process './macchina-linux'. Reason:`
> `exec: Exec format error`
> `The file './macchina-linux' is marked as an executable but could not be run by the operating system.`

I forgot to mention that `macchina-linux` only runs on **x86_64** machines, and Raspberry Pi is probably ARM right?

**Comment by Dan1jel** [comment]
> > Thank you so much for the great explinaton. But when i try this, all i get is -
> > ` ~ $ ./macchina-linux`
> > `Failed to execute process './macchina-linux'. Reason:`
> > `exec: Exec format error`
> > `The file './macchina-linux' is marked as an executable but could not be run by the operating system.`
> 
> I forgot to mention that `macchina-linux` (from the releases page) only runs on **x86_64** machines, and Raspberry Pi is probably ARM right?
> 
> EDIT: I'll create an action that builds `macchina` for ARM machines.

That is correct, i was just about to update my post but yes its because Raspberry is ARM based that it wont work. 

That would be great! And more people can enjoy this as well with ARM machines.

**Comment by grtcdr** [comment]
Oops, GitHub doesn't offer ARM runners and I don't have any ARM machines lying around to make a self-hosted runner, and creating an ARM VM on my x86_64 machine is beyond my realm of knowledge 😕

**Comment by Dan1jel** [comment]
> Oops, GitHub doesn't offer ARM runners and I don't have any ARM machines lying around to make a self-hosted runner, and creating an ARM VM on my x86_64 machine is beyond my realm of knowledge 😕

Aaaw that's sad :/ hope that gets change in the future but thanks for looking in to it anyway.

**Comment by uttarayan21** [comment]
There are two ways you can get it to run on your rpi
- cargo supports cross compiling directly if you specify a `linker` and an `ar` for the target.
- You can use [`cross`](https://github.com/rust-embedded/cross) which makes it super easy to cross compile.

Use this to list rust targets and then
```bash
rustup target list | grep arm
```

Using cross build with
```
cross build --target=arm-unknown-linux-gnueabi --release
```
Then copy the binary over to your Raspberry pi.

**Comment by uttarayan21** [comment]
> Oops, GitHub doesn't offer ARM runners and I don't have any ARM machines lying around to make a self-hosted runner, and creating an ARM VM on my x86_64 machine is beyond my realm of knowledge 😕

That is true but there are a lot of arm targets and I'm not sure for which one to build lol.
```bash
arm-linux-androideabi
arm-unknown-linux-gnueabi
arm-unknown-linux-gnueabihf
arm-unknown-linux-musleabi
arm-unknown-linux-musleabihf
armebv7r-none-eabi
armebv7r-none-eabihf
armv5te-unknown-linux-gnueabi
armv5te-unknown-linux-musleabi
armv7-linux-androideabi
armv7-unknown-linux-gnueabi
armv7-unknown-linux-gnueabihf
armv7-unknown-linux-musleabi
armv7-unknown-linux-musleabihf
armv7a-none-eabi
armv7r-none-eabi
armv7r-none-eabihf
```

If you want I can try to setup a github action for cross compiling for arm targets.

**Comment by grtcdr** [comment]
> > Oops, GitHub doesn't offer ARM runners and I don't have any ARM machines lying around to make a self-hosted runner, and creating an ARM VM on my x86_64 machine is beyond my realm of knowledge confused
> 
> That is true but there are a lot of arm targets and I'm not sure for which one to build lol.
> 
> ```shell
> arm-linux-androideabi
> arm-unknown-linux-gnueabi
> arm-unknown-linux-gnueabihf
> arm-unknown-linux-musleabi
> arm-unknown-linux-musleabihf
> armebv7r-none-eabi
> armebv7r-none-eabihf
> armv5te-unknown-linux-gnueabi
> armv5te-unknown-linux-musleabi
> armv7-linux-androideabi
> armv7-unknown-linux-gnueabi
> armv7-unknown-linux-gnueabihf
> armv7-unknown-linux-musleabi
> armv7-unknown-linux-musleabihf
> armv7a-none-eabi
> armv7r-none-eabi
> armv7r-none-eabihf
> ```
> 
> If you want I can try to setup a github action for cross compiling for arm targets.

Yeah, give it a go!

I personally didn't feel comfortable making a mess out of it, because as you mentioned, there's so many ARM targets out there, and that was partly what made me so confused.

**Comment by Dan1jel** [comment]
> There are two ways you can get it to run on your rpi
> - cargo supports cross compiling directly if you specify a `linker` and an `ar` for the target.
> - You can use [`cross`](https://github.com/rust-embedded/cross) which makes it super easy to cross compile.
> 
> Use this to list rust targets and then
> ```bash
> rustup target list | grep arm
> ```
> 
> Using cross build with
> ```
> cross build --target=arm-unknown-linux-gnueabi --release
> ```
> Then copy the binary over to your Raspberry pi.

Great tip but i just can't get it to work.

**Comment by grtcdr** [comment]
Where exactly are you finding problems?

**Comment by Dan1jel** [comment]
> Where exactly are you finding problems?

By doing/trying these commands, my system don't know what to do with these commands. 

```bash
 rustup target list | grep arm
 ```

Using cross build with
 ```
 cross build --target=arm-unknown-linux-gnueabi --release
 ```

**Comment by grtcdr** [comment]
> > Where exactly are you finding problems?
> 
> By doing/trying these commands, my system don't know what to do with these commands.
> 
> ```shell
>  rustup target list | grep arm
> ```

You may not have rustup installed then. But here's the output of that command:
```
arm-linux-androideabi
arm-unknown-linux-gnueabi
arm-unknown-linux-gnueabihf
arm-unknown-linux-musleabi
arm-unknown-linux-musleabihf
armebv7r-none-eabi
armebv7r-none-eabihf
armv5te-unknown-linux-gnueabi
armv5te-unknown-linux-musleabi
armv7-linux-androideabi
armv7-unknown-linux-gnueabi
armv7-unknown-linux-gnueabihf (installed)
armv7-unknown-linux-musleabi
armv7-unknown-linux-musleabihf
armv7a-none-eabi
armv7r-none-eabi
armv7r-none-eabihf
```

> ```
> cross build --target=arm-unknown-linux-gnueabi --release
> ```

I don't know why this wouldn't work if you've correctly installed both `cross` and `docker`.

**Comment by uttarayan21** [comment]
Another thing, depending on the version of your Raspberry PI, you might need to use `--target=aarch64-unknown-linux-gnu`.

**Comment by Dan1jel** [comment]
> > > Where exactly are you finding problems?
> > 
> > By doing/trying these commands, my system don't know what to do with these commands.
> > 
> > ```shell
> >  rustup target list | grep arm
> > ```
> 
> You may not have rustup installed then. But here's the output of that command:
> ```
> arm-linux-androideabi
> arm-unknown-linux-gnueabi
> arm-unknown-linux-gnueabihf
> arm-unknown-linux-musleabi
> arm-unknown-linux-musleabihf
> armebv7r-none-eabi
> armebv7r-none-eabihf
> armv5te-unknown-linux-gnueabi
> armv5te-unknown-linux-musleabi
> armv7-linux-androideabi
> armv7-unknown-linux-gnueabi
> armv7-unknown-linux-gnueabihf (installed)
> armv7-unknown-linux-musleabi
> armv7-unknown-linux-musleabihf
> armv7a-none-eabi
> armv7r-none-eabi
> armv7r-none-eabihf
> ```
> 
> > ```
> > cross build --target=arm-unknown-linux-gnueabi --release
> > ```
> 
> I don't know why this wouldn't work if you've correctly installed both `cross` and `docker` (with the docker.service running in the background).

Rustup and cross is not available on ```apt install```

It would be nice to have macchina and i could maybe get it to work eventually but my thought was that it maybe could be easy to get this running. Also an idea was to maybe do a easy script to install it again (if i get a new harddrive or rpi), this is making it a little hard to have on a simple install script in the future.

**Comment by uttarayan21** [comment]
Well I'm working on a github action right now to compile for arm and a few other targets so you can directly download binaries.
I'll update when its done.

**Comment by uttarayan21** [comment]
@Dan1jel you can try to download [macchina-linux-aarch64](https://github.com/uttarayan21/macchina/releases/download/v0.8.1/macchina-linux-aarch64) until a new tag is available on this repo.

**Comment by grtcdr** [comment]
> @Dan1jel you can try to download [macchina-linux-aarch64](https://github.com/uttarayan21/macchina/releases/download/v0.8.1/macchina-linux-aarch64) until a new tag is available on this repo.

I'll release a new version so he doesn't have to wait too long for the next release.

**Comment by Dan1jel** [comment]
> > @Dan1jel you can try to download [macchina-linux-aarch64](https://github.com/uttarayan21/macchina/releases/download/v0.8.1/macchina-linux-aarch64) until a new tag is available on this repo.
> 
> I'll release a new version so he doesn't have to wait too long for the next release.

I'm really glad that you all being this helpful, but i still can't use this. 

```~ $ ./macchina-linux-aarch64```
```Failed to execute process './macchina-linux-aarch64'. Reason:
exec: Exec format error```
```The file './macchina-linux-aarch64' is marked as an executable but could not be run by the operating system.```

**Comment by uttarayan21** [comment]
Can you run `uname -m` in the rpi and post the output ?

I can then try to post a binary for your hardware target.

**Comment by Dan1jel** [comment]
> Can you run `uname -m` in the rpi and post the output ?
> 
> I can then try to post a binary for your hardware target.

Sure thing, `armv7l` (Raspberry 3B)

**Comment by uttarayan21** [comment]
Can you try this binary ? [macchina-linux-rpi3b](https://github.com/uttarayan21/macchina/releases/download/v0.8.1/macchina-linux-rpi3b)
This is built for target `armv7-unknown-linux-gnueabihf` which is what Raspbian should be.

**Comment by Dan1jel** [comment]
> Can you try this binary ? [macchina-linux-rpi3b](https://github.com/uttarayan21/macchina/releases/download/v0.8.1/macchina-linux-rpi3b)
> This is built for target `armv7-unknown-linux-gnueabihf` which is what Raspbian should be.

This works like a charm! thank you so much for quick reply and helping me with this.

**Comment by uttarayan21** [comment]
No problem :) 
Happy to help.
