### ISSUE TITLE
[BUG] macchina doctor output not colors in windows.

### ISSUE THREAD

**Issue by uttarayan21** [Macchina-CLI/macchina#92]
**Describe the bug**
macchina on windows has no colors in doctor output.

Also the ascii art is really hard to see in default PowerShell

I honestly have no clue how windows handles it color codes so I don't know how to fix it.

**To Reproduce**
1. .\macchina-windows.exe

**Expected behavior**
Colored output like in linux/mac

**Screenshots**
![windows](https://user-images.githubusercontent.com/18732700/118558709-a531c300-b784-11eb-9a9e-380bb80bf94f.png)

**System Information**
You don't have to provide this information if you're not comfortable doing so, but it'll help us solve the issue a lot faster.
 - Distribution: Windows 10 Pro
 - Desktop Environment: null
 - Operating System: Windows 10 Pro
 - Terminal: PowerShell
 - Macchina's version: 0.8.0

**Comment by grtcdr** [comment]
We're using [colored](https://github.com/mackwic/colored) to easily color text for doctor, I guess there's something wrong on their part, I'll check out their issues for a similar problem and if nothing comes up I'll file one!

Thanks :)

**Comment by grtcdr** [comment]
[Here's what I found](https://github.com/mackwic/colored/issues/59)

**Comment by uttarayan21** [comment]
I took a look at that issue. I'll might do some more tests later.

**Comment by grtcdr** [comment]
Okay :)

**Comment by grtcdr** [comment]
colored has had no progress in this, we can drop it in favor of a more OS/terminal-agnostic color crated.
