### ISSUE TITLE
[Discussion] Manually writing completions

### ISSUE THREAD

**Issue by uttarayan21** [Macchina-CLI/macchina#93]
I made the auto complete for custom themes work with the fish shell completions.
It needed a little bit on manual tweaking.

As long as there are no breaking changes this can probably be automated.
I can probably make a patch that would apply to the `macchina.fish` generated from clap but I have no clue where to apply it.
The best way to apply it would probably be in the PKGBUILD or whatever packaging system is being used.

![complete](https://user-images.githubusercontent.com/18732700/118617120-f3c07b00-b7df-11eb-8250-142162926510.png)

**Comment by grtcdr** [comment]
This is a nice thing to have, but if it's a hassle to get working and keep it working for the next releases, then it's really not necessary because `--list-themes` sort of compensates for the lack of auto-complete.

**Comment by uttarayan21** [comment]
> This is a nice thing to have, but if it's a hassle to get working and keep it working for the next releases, then it's really not necessary because --list-themes sort of compensates for the lack of auto-complete.

Yeah that is true.

I'll close this issue for now , but If someone wants autocomplete then we can revisit this again in the future.
