### ISSUE TITLE
[BUG] no_separator is not producing written out information (macchina.toml config file)

### ISSUE THREAD

**Issue by Staubgeborener** [Macchina-CLI/macchina#94]
**Describe the bug**
I would like to display some information with macchina. These should be without a separator and the categories should be written out (for example, "machine" should be written instead of "mac", etc.).

`no_separator = true` gives the error message "conflicting keys in config file: separator_color and no_separator". 
So I commented out `separator_color`. Which in itself also works without an error message, but now the information is all abbreviated (Host = Hos, Machine = Mac, etc.). The `short_shell` parameter doesn't solve the problem either, regardless of whether the flag is `true` or `false`, the output remains the same.

Long story short: I only get some written out information together with a "conflict" error message but never with `no_separator = true`.

**To Reproduce**
1. create macchina.toml file with [macchina.toml example](https://github.com/Macchina-CLI/macchina/blob/main/macchina.toml)
2. edit config file: `no_separator = true` (line [7](https://github.com/Macchina-CLI/macchina/blob/main/macchina.toml#L7) )`#separator_color` (line [63](https://github.com/Macchina-CLI/macchina/blob/main/macchina.toml#L63))
3. run `macchina`

**Expected behavior**
Display some information without separator and with written out categories ("machine" instead of "mac", etc.)

**Screenshots**
![screen1](https://user-images.githubusercontent.com/28908603/118619032-bd6d0680-b7b3-11eb-85c7-6bdb13ef69ce.png)
![screen2](https://user-images.githubusercontent.com/28908603/118619029-bcd47000-b7b3-11eb-9796-e879bdb53459.png)

**`macchina --doctor` output**
![doctor](https://user-images.githubusercontent.com/28908603/118619162-db3a6b80-b7b3-11eb-8071-38ff6cb845c5.png)

**System Information**
You don't have to provide this information if you're not comfortable doing so, but it'll help us solve the issue a lot faster.
 - Distribution: Parrot 4.11
 - Desktop: Environment i3
 - Terminal: Kitty
 - Macchina's version: 0.8.1

**Comment by uttarayan21** [comment]
> Display some information without separator and with written out categories ("machine" instead of "mac", etc.)

You mean like this ?

![Screenshot from 2021-05-18 14-36-33](https://user-images.githubusercontent.com/18732700/118624073-751b0c00-b7e6-11eb-86aa-dfa052f6bedf.png)
