### ISSUE TITLE
[Themes] Do not allow custom themes to use built-in theme names

### ISSUE THREAD

**Issue by grtcdr** [Macchina-CLI/macchina#95]
Macchina will probably get confused when your custom theme has the same name as the built-in theme and choose one over the other, so to avoid this, a conflict warning message needs to be printed to the screen notifying the user that their custom theme name isn't valid as it's already in use by a built-in theme.

EDIT: Currently, Macchina defaults back to the default theme when this issue is encountered, but the error message isn't helpful.

**Comment by uttarayan21** [comment]
> EDIT: Currently, Macchina defaults back to the default theme when this issue is encountered, but the error message isn't helpful.

For me `macchina` gives priority to the inbuilt theme first and then to the Custom theme ( I get no error).

What should we do in case of a conflict ?

**Comment by grtcdr** [comment]
> For me `macchina` gives priority to the inbuilt theme first and then to the Custom theme ( I get no error).

Oh yeah, me too! But that's sort of the issue I'd like to avoid, by notifying the user that Macchina will not use their custom theme if the name is in use by a default theme.

> What should we do in case of a conflict ?

A warning when running `macchina`, and another when invoking `--list-themes`.

**Comment by uttarayan21** [comment]
So doing something similar to the pseudo code should work.
```rust 
for theme in Themes::variants() {
    if exists(dirs::data_local_dir()/macchina/themes/{theme}) {
        println!("Warning: Custom theme with conflicting inbuilt theme name found");
    }
}
```

**Comment by uttarayan21** [comment]
Also this will try to read the filesystem like 5 times so It might get slow.
So we might only want to display it when using `--list-themes`

**Comment by grtcdr** [comment]
Yeah, this is what I tried to do a couple hours ago but failed to make it work, it just wouldn't show me the error message for some reason.

**Comment by grtcdr** [comment]
> Also this will try to read the filesystem like 5 times so It might get slow if a harddrive is being used.
> So we might only want to display it when using `--list-themes`

Meaning we create a vector of available themes and check if there are any repeating theme names or something of this sort?

**Comment by uttarayan21** [comment]
> Meaning we create a vector of available themes and check if there are any repeating theme names or something of this sort?

No just by doing normal filesystem check but only in case of `--list-themes` since performance is not critical when listing themes.
But when running macchina normally it might get slowed down if we have to check multiple files.

> Should we consider X and x to be the same theme names?

Well now all theme names are case sensitive so they can be considered different.

**Comment by grtcdr** [comment]
> > Meaning we create a vector of available themes and check if there are any repeating theme names or something of this sort?
> 
> No, I meant doing normal filesystem checks but only in case of `--list-themes` since performance is not critical when listing themes.
> But when running macchina normally it might get slowed down if we have to check multiple files so we don't display the warning then.

You're right, I'll try and make this work for `--list-themes` only.

> > Should we consider X and x to be the same theme names?
> 
> Well now all theme names are case sensitive so they can be considered different.

Okay.

**Comment by uttarayan21** [comment]
I'm done Implementing with both of them already

I'll open a pull request soon

**Comment by grtcdr** [comment]
That's awesome :rocket:
